"""
tricorder build — generate the interactive explorer from .tricorder/ artifacts

Reads learnings.json (Level 3) and writes explorer/data.js so the static
HTML explorer reflects the current analysis.

Optionally applies a name map from ~/.tricorder/<owner>__<repo>-name-map.json.

Usage:
  tricorder build                          # infers repo from git remote
  tricorder build OWNER/REPO
  tricorder build --out PATH/data.js       # custom output path
  tricorder build --name-map PATH          # explicit name map
  tricorder build --open                   # open explorer in browser after build
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import webbrowser
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Category / radar constants (must match explorer app)
# ---------------------------------------------------------------------------

CATEGORIES = [
    "grain", "naming", "testing", "documentation", "style",
    "performance", "modeling", "schema", "business-logic",
    # extended for non-analytics lenses
    "structure", "security", "other",
]

CATEGORY_GROUP = {
    "grain": "data", "naming": "pattern", "testing": "tool",
    "documentation": "pattern", "style": "pattern", "performance": "data",
    "modeling": "data", "schema": "data", "business-logic": "pattern",
    "structure": "pattern", "security": "tool", "other": "pattern",
}

CATEGORY_KEYWORDS = {
    "grain":          ["grain", "dedup", "fanout", "granularity", "row count"],
    "naming":         ["naming", "convention", "snake_case", "prefix", "stg_", "fct_", "dim_"],
    "testing":        ["test", "uniqueness", "not_null", "referential", "primary key", "coverage"],
    "documentation":  ["documentation", "docs", "description", "comment", "schema.yml", "readme"],
    "style":          ["style", "cte", "readability", "formatting", "alias", "select *"],
    "performance":    ["performance", "cost", "partition", "clustering", "scan", "expensive"],
    "modeling":       ["incremental", "materialization", "staging", "mart", "intermediate", "scd"],
    "schema":         ["source freshness", "schema change", "breaking change", "freshness", "contract"],
    "business-logic": ["business logic", "domain", "derived field", "conditional", "spec"],
    "structure":      ["structure", "folder", "organization", "module", "layer", "layout"],
    "security":       ["security", "auth", "permission", "injection", "secret", "credential", "xss"],
    "other":          [],
}

FREQ_MAP = {"always": 90, "often": 70, "sometimes": 45, "rarely": 22, "never": 5}
BASELINE = 8


def taxonomy_from_lens(lens) -> dict:
    """Categories, colour groups, radar axes, and keyword map derived from a Lens."""
    cats = lens.category_ids
    groups = {c: lens.category_group(c) for c in cats}
    radar = [c for c in lens.core_category_ids if c != "other"] or [c for c in cats if c != "other"][:9]
    keywords: dict[str, list[str]] = {}
    for c in lens.categories:
        kws = list(c.get("keywords") or [])
        kws.append(c["id"].replace("-", " "))
        kws += CATEGORY_KEYWORDS.get(c["id"], [])
        keywords[c["id"]] = sorted(set(k for k in kws if k))
    return {"categories": cats, "groups": groups, "radar": radar, "keywords": keywords,
            "lens": lens.summary()}


def _taxonomy_for(learnings: dict) -> dict:
    """Lens-driven taxonomy when the learnings name a lens; legacy dbt set otherwise."""
    info = learnings.get("lens") or {}
    name = info.get("name")
    if name:
        try:
            from tricorder.lenses import load_lens
            tax = taxonomy_from_lens(load_lens(name))
            tax["lens"] = {**tax["lens"], **{k: v for k, v in info.items() if k not in tax["lens"]}}
            return tax
        except Exception as e:  # lens missing on this machine: fall back but say so
            print(f"  ⚠ lens {name!r} not loadable ({e}); falling back to the legacy category set")
    cats = [c for c in CATEGORIES if c in CATEGORY_GROUP or c == "other"]
    return {"categories": cats, "groups": CATEGORY_GROUP,
            "radar": [c for c in cats if c != "other"][:9], "keywords": CATEGORY_KEYWORDS,
            "lens": info or None}


JS_TEMPLATE = """\
// Generated by tricorder build — {generated}
// Repo: {repo}  |  Version: {version}
window.TRICORDER_DATA = (function () {{

  const CATEGORIES = {categories};
  const RADAR_CATEGORIES = {radar_categories};
  const CATEGORY_GROUP = {category_group};
  const lens = {lens_js};

  const patterns = {patterns};

  const reviewers = {reviewers};

  const authors = {authors};

  const gaps = {gaps};

  return {{
    repo:             {repo_js},
    window:           {window_js},
    pr_count:         {pr_count},
    prs_with_reviews: {prs_with_reviews},
    contributors:     {contributors},
    visibility:       {visibility_js},
    version:          {version_js},
    lens,
    CATEGORIES,
    RADAR_CATEGORIES,
    CATEGORY_GROUP,
    patterns,
    reviewers,
    authors,
    gaps,
  }};
}})();
"""


# ---------------------------------------------------------------------------
# Name map
# ---------------------------------------------------------------------------

def _load_name_map(repo: str, explicit_path: str | None) -> dict:
    if explicit_path:
        p = Path(explicit_path).expanduser()
        if p.exists():
            return json.loads(p.read_text())
        print(f"  Name map not found at {p} — proceeding without.", file=sys.stderr)
        return {}

    slug = repo.replace("/", "__")
    auto = Path.home() / ".tricorder" / f"{slug}-name-map.json"
    if auto.exists():
        print(f"  Name map: {auto}")
        return json.loads(auto.read_text())
    return {}


def _apply_map(obj, name_map: dict):
    if not name_map:
        return obj
    if isinstance(obj, str):
        return name_map.get(obj, obj)
    if isinstance(obj, list):
        return [_apply_map(i, name_map) for i in obj]
    if isinstance(obj, dict):
        return {k: _apply_map(v, name_map) for k, v in obj.items()}
    return obj


# ---------------------------------------------------------------------------
# Radar / category inference
# ---------------------------------------------------------------------------

def _infer_category_freq(focus_areas: list, categories: list | None = None,
                         keywords: dict | None = None) -> dict:
    categories = categories or CATEGORIES
    keyword_map = keywords or CATEGORY_KEYWORDS
    scores = {cat: BASELINE for cat in categories}
    for fa in focus_areas:
        text = ((fa.get("area") or "") + " " + (fa.get("category") or "") + " "
                + (fa.get("standard_citation") or "")).lower()
        freq_val = FREQ_MAP.get(fa.get("frequency", "sometimes"), 45)
        # a lens-aware Phase 2 tags each focus area with a category directly
        if fa.get("category") in scores:
            scores[fa["category"]] = max(scores[fa["category"]], freq_val)
        for cat, kws in keyword_map.items():
            if cat in scores and any(kw in text for kw in kws):
                scores[cat] = max(scores[cat], freq_val)
    return scores


# ---------------------------------------------------------------------------
# Data loaders from v2 .tricorder/ artifacts
# ---------------------------------------------------------------------------

def _load_patterns(learnings: dict, name_map: dict, top_n: int = 20) -> list:
    raw_patterns = learnings.get("patterns", [])
    if not raw_patterns:
        return []

    # Deduplicate by signal text
    seen: dict[str, dict] = {}
    for p in raw_patterns:
        signal = (p.get("signal") or "").strip()
        if not signal or len(signal) < 10:
            continue
        key = signal.lower()[:120]
        if key not in seen:
            seen[key] = {
                "signal":            signal,
                "category":          p.get("category", "other"),
                "maturity":          p.get("maturity", "guidance"),
                "standard_citation": p.get("standard_citation"),
                "reviewer":          p.get("reviewer", ""),
                "author":            p.get("author", ""),
                "count":             1,
                "evidence":          [],
            }
            ev = p.get("comment_evidence", [])
            for q in ev[:2]:
                if len(q) > 20:
                    seen[key]["evidence"].append({
                        "pr": "", "date": "", "author": p.get("author", ""), "quote": q[:300]
                    })
        else:
            seen[key]["count"] += 1

    maturity_levels = ["judgment", "guidance", "convention", "rule", "deterministic"]
    max_per_maturity = max(2, (top_n + len(maturity_levels) - 1) // len(maturity_levels))
    max_per_reviewer = 3

    maturity_quota: dict[str, int] = {m: 0 for m in maturity_levels}
    reviewer_quota: dict[str, int] = {}
    selected = []
    seen_signals: set[str] = set()

    for p in sorted(seen.values(), key=lambda x: x["count"], reverse=True):
        if len(selected) >= top_n:
            break
        m = p["maturity"]
        rev = _apply_map(p.get("reviewer", ""), name_map)
        if maturity_quota.get(m, 0) >= max_per_maturity:
            continue
        if reviewer_quota.get(rev, 0) >= max_per_reviewer:
            continue
        if p["signal"] in seen_signals:
            continue
        selected.append(p)
        seen_signals.add(p["signal"])
        maturity_quota[m] = maturity_quota.get(m, 0) + 1
        reviewer_quota[rev] = reviewer_quota.get(rev, 0) + 1

    # fill remaining
    for p in sorted(seen.values(), key=lambda x: x["count"], reverse=True):
        if len(selected) >= top_n:
            break
        if p["signal"] in seen_signals:
            continue
        if maturity_quota.get(p["maturity"], 0) >= max_per_maturity:
            continue
        selected.append(p)
        seen_signals.add(p["signal"])
        maturity_quota[p["maturity"]] = maturity_quota.get(p["maturity"], 0) + 1

    for p in selected:
        p.pop("count", None)

    return _apply_map(selected, name_map)


def _load_reviewers(learnings: dict, name_map: dict, taxonomy: dict | None = None) -> list:
    _cats = (taxonomy or {}).get("categories")
    _kws = (taxonomy or {}).get("keywords")
    reviewers = []
    for raw in learnings.get("reviewer_profiles", []):
        if raw.get("_error"):
            continue
        login = _apply_map(raw.get("reviewer") or raw.get("_reviewer", "unknown"), name_map)
        focus = raw.get("primary_focus_areas", [])
        blind = raw.get("apparent_blind_spots", [])
        reviewers.append({
            "login":               login,
            "review_style":        raw.get("review_style", "advisory"),
            "signal_quality":      raw.get("signal_quality", "low"),
            "primary_focus_areas": _apply_map(
                [{"area": a.get("area", ""), "frequency": a.get("frequency", "sometimes")}
                 for a in focus],
                name_map,
            ),
            "apparent_blind_spots": _apply_map(
                [{"area": b.get("area", ""), "basis": b.get("basis", "")}
                 for b in blind],
                name_map,
            ),
            "category_freq": _infer_category_freq(focus, _cats, _kws),
        })

    sig_rank = {"high": 0, "medium": 1, "low": 2}
    reviewers.sort(key=lambda r: (sig_rank.get(r["signal_quality"], 9), r["login"]))
    return reviewers


def _load_authors(learnings: dict, name_map: dict) -> list:
    authors = []
    for raw in learnings.get("author_profiles", []):
        if raw.get("_error"):
            continue
        login = _apply_map(raw.get("author") or raw.get("_author", "unknown"), name_map)
        authors.append({
            "login":       login,
            "trajectory":  raw.get("trajectory", "insufficient-data"),
            "strengths":   _apply_map(
                [{"area": s.get("area", ""), "persistence": s.get("persistence", "consistent")}
                 for s in raw.get("strengths", [])],
                name_map,
            ),
            "growth_areas": _apply_map(
                [{"area": g.get("area", ""),
                  "persistence": g.get("persistence", "consistent"),
                  "support_recommendation": g.get("support_recommendation", "")}
                 for g in raw.get("growth_areas", [])],
                name_map,
            ),
        })

    traj_rank = {"improving": 0, "stable": 1, "regressing": 2, "insufficient-data": 3}
    authors.sort(key=lambda a: (traj_rank.get(a["trajectory"], 9), a["login"]))
    return authors


def _load_gaps(learnings: dict, name_map: dict) -> list:
    crit_map = {"coverage_gap": 1, "blind_spot": 2, "knowledge_gap": 3}
    result = []
    for g in learnings.get("gaps", []):
        result.append({
            "area":              g.get("area", ""),
            "gap_type":          g.get("gap_type", "coverage_gap"),
            "criticality":       crit_map.get(g.get("gap_type", ""), 2),
            "standard_citation": g.get("standard_citation"),
            "recommendation":    g.get("recommendation", ""),
        })
    return _apply_map(result, name_map)


# ---------------------------------------------------------------------------
# Infer repo from remote
# ---------------------------------------------------------------------------

def _infer_repo_from_remote() -> str | None:
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode != 0:
            return None
        url = result.stdout.strip()
        for prefix in ("git@github.com:", "https://github.com/", "http://github.com/"):
            if url.startswith(prefix):
                slug = url[len(prefix):].removesuffix(".git")
                if "/" in slug:
                    return slug
    except Exception:
        pass
    return None


def _read_version() -> str:
    here = Path(__file__).parent.parent.parent
    vf = here / "VERSION"
    return vf.read_text().strip() if vf.exists() else "dev"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run(args: list[str]) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        prog="tricorder build",
        description="Generate the interactive HTML explorer from .tricorder/ artifacts.",
    )
    parser.add_argument("repo", nargs="?", default=None,
                        help="OWNER/REPO (default: inferred from git remote)")
    parser.add_argument("--out", default=None, metavar="PATH",
                        help="Path for data.js (default: explorer/data.js in the tricorder install dir)")
    parser.add_argument("--name-map", default=None, metavar="PATH",
                        help="Path to name-map JSON (default: ~/.tricorder/<owner>__<repo>-name-map.json)")
    parser.add_argument("--no-anonymize", action="store_true",
                        help="Skip name map even if one is auto-detected")
    parser.add_argument("--open", action="store_true",
                        help="Open the explorer in a browser after building (starts a local server)")
    parser.add_argument("--port", type=int, default=7372, metavar="PORT",
                        help="Port for the local server (default: 7372)")
    parser.add_argument("--tricorder-dir", default=None, metavar="DIR",
                        help="Path to .tricorder/ directory (default: .tricorder/ in cwd)")

    parsed = parser.parse_args(args)

    from tricorder.config import repo_dir as _repo_dir, load_config as _load_tri_config, get as _cfg_get
    tri_base = Path.cwd() / ".tricorder"

    # build renders data that's *already on disk* — unlike analyze/learn/interpret/improve,
    # which decide what repo to newly process, build must not let cwd's git remote override
    # a repo that was actually analyzed into this .tricorder/ directory. Precedence here is
    # CLI arg -> config current_repo (if its cache has data) -> git remote (if its cache has
    # data) -> config current_repo (as a label even without data, for a clear error message).
    def _has_learnings(slug: str | None) -> bool:
        return bool(slug) and (_repo_dir(tri_base, slug) / "learnings.json").exists()

    current_repo = _cfg_get(_load_tri_config(tri_base), "current_repo")
    git_repo = _infer_repo_from_remote()

    if parsed.repo:
        repo, repo_source = parsed.repo, "arg"
    elif _has_learnings(current_repo):
        repo, repo_source = current_repo, "config"
    elif _has_learnings(git_repo):
        repo, repo_source = git_repo, "git"
    else:
        repo, repo_source = (current_repo or git_repo), "config" if current_repo else "git"

    if repo_source == "config" and repo:
        print(f"  Repo: {repo}  (from .tricorder/config.yml — pass OWNER/REPO to override)")
    elif repo_source == "git":
        print(f"  Repo: {repo}  (inferred from git remote — pass OWNER/REPO if this isn't the analyzed repo)")
    repo = repo or "unknown/repo"

    # Resolve .tricorder dir — per-repo subdir, matching analyze/learn/interpret/improve
    if parsed.tricorder_dir:
        tri_dir = Path(parsed.tricorder_dir).expanduser().resolve()
    elif repo != "unknown/repo":
        tri_dir = _repo_dir(tri_base, repo)
    else:
        tri_dir = tri_base

    learnings_path = tri_dir / "learnings.json"
    if not learnings_path.exists():
        print(f"learnings.json not found in {tri_dir}", file=sys.stderr)
        print("Run tricorder learn first.", file=sys.stderr)
        return 1

    # Resolve output path
    if parsed.out:
        out_path = Path(parsed.out).expanduser().resolve()
    else:
        # Default: explorer/data.js relative to the tricorder package install
        install_dir = Path(__file__).parent.parent.parent
        out_path = install_dir / "explorer" / "data.js"

    # Name map
    name_map: dict = {}
    if not parsed.no_anonymize:
        name_map = _load_name_map(repo, parsed.name_map)

    print(f"\ntricorder build — {repo}")
    print(f"  Source:   {tri_dir}")
    print(f"  Output:   {out_path}")
    if name_map:
        print(f"  Name map: {len(name_map)} aliases applied")
    print()

    # Load artifacts
    learnings = json.loads(learnings_path.read_text())

    # Load manifest / date range from review-patterns.json if available
    patterns_meta_path = tri_dir / "review-patterns.json"
    patterns_meta = json.loads(patterns_meta_path.read_text()) if patterns_meta_path.exists() else {}

    pr_count = patterns_meta.get("pr_count") or learnings.get("pattern_count", 0)
    date_range = patterns_meta.get("date_range", {})
    window_str = (
        f"{date_range.get('from', '')} → {date_range.get('to', '')}"
        if date_range else "unknown window"
    )
    contributors = [
        _apply_map(r.get("reviewer") or r.get("_reviewer", ""), name_map)
        for r in learnings.get("reviewer_profiles", [])
        if not r.get("_error")
    ]

    print("  Loading patterns ...", end=" ", flush=True)
    patterns = _load_patterns(learnings, name_map)
    print(f"{len(patterns)} selected")

    taxonomy = _taxonomy_for(learnings)
    if taxonomy.get("lens"):
        print(f"  Lens:     {taxonomy['lens'].get('name')} ({len(taxonomy['categories'])} categories)")

    print("  Loading reviewers ...", end=" ", flush=True)
    reviewers = _load_reviewers(learnings, name_map, taxonomy)
    print(f"{len(reviewers)} profiles")

    print("  Loading authors ...", end=" ", flush=True)
    authors = _load_authors(learnings, name_map)
    print(f"{len(authors)} profiles")

    print("  Loading gaps ...", end=" ", flush=True)
    gaps = _load_gaps(learnings, name_map)
    print(f"{len(gaps)} gaps")

    version = _read_version()
    prs_with_reviews = sum(
        1 for p in learnings.get("patterns", [])
        if p.get("author")
    ) or pr_count

    js = JS_TEMPLATE.format(
        generated        = datetime.now().strftime("%Y-%m-%d %H:%M"),
        version          = version,
        repo             = repo,
        categories       = json.dumps(taxonomy["categories"]),
        radar_categories = json.dumps(taxonomy["radar"]),
        category_group   = json.dumps(taxonomy["groups"]),
        lens_js          = json.dumps(taxonomy["lens"]),
        patterns         = json.dumps(patterns, indent=2),
        reviewers        = json.dumps(reviewers, indent=2),
        authors          = json.dumps(authors, indent=2),
        gaps             = json.dumps(gaps, indent=2),
        repo_js          = json.dumps(repo),
        window_js        = json.dumps(window_str),
        pr_count         = pr_count,
        prs_with_reviews = prs_with_reviews,
        contributors     = json.dumps(contributors),
        visibility_js    = json.dumps("private" if not name_map else "team"),
        version_js       = json.dumps(version),
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(js)

    explorer_dir = out_path.parent
    explorer_html = explorer_dir / "index.html"
    url = f"http://localhost:{parsed.port}/"

    print()
    print(f"  ✓ {out_path}")
    print()

    if parsed.open and explorer_html.exists():
        _serve_and_open(explorer_dir, parsed.port, url)
    else:
        print(f"  View: tricorder build --open")
        print(f"  Or:   cd {explorer_dir} && python3 -m http.server {parsed.port}")
        print()

    return 0


def _serve_and_open(explorer_dir: Path, port: int, url: str) -> None:
    """Start a local HTTP server and open the browser. Ctrl-C to stop."""
    import http.server
    import threading

    os.chdir(explorer_dir)

    handler = http.server.SimpleHTTPRequestHandler
    handler.log_message = lambda *a: None  # silence request logs

    try:
        server = http.server.HTTPServer(("", port), handler)
    except OSError:
        # Port in use — just open with whatever is already running there
        print(f"  Port {port} already in use — opening {url}")
        webbrowser.open(url)
        return

    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()

    print(f"  Serving explorer at {url}")
    print(f"  Press Ctrl-C to stop.")
    print()
    webbrowser.open(url)

    try:
        thread.join()
    except KeyboardInterrupt:
        print("\n  Server stopped.")
        server.shutdown()
