"""
tricorder skills forge

Takes skill-shaped roadmap items, generates SKILL.md files via LLM,
and lands them in a target GitHub repo as a branch + PR.

Flow:
  1. Ask for target repo (OWNER/REPO)
  2. Clone repo to temp dir
  3. For each skill item: generate SKILL.md via LLM
  4. Create GitHub issue for tracking (soft-fail)
  5. Create branch, write files, commit, push
  6. Create PR via gh CLI
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


MAX_TOKENS = 4096

SYSTEM_SKILL = """\
You are writing a SKILL.md file for a Claude Code agent skill.

A skill is a reusable capability that an AI assistant can invoke during
code review, authoring, or planning. It is defined by:
  1. When to trigger it (trigger phrases)
  2. What it does step-by-step
  3. What inputs it needs
  4. What outputs it produces

The SKILL.md format has a YAML front matter block followed by a Markdown body.

YAML FRONT MATTER FIELDS:
  name:         slug, lowercase, hyphenated
  version:      "1.0.0"
  description:  one-sentence summary (used for routing)
  triggers:     list of natural-language phrases that invoke this skill
  inputs:       what the skill needs to run
  outputs:      what the skill produces
  visibility:   private | team | public

MARKDOWN BODY SECTIONS:
  ## Purpose          — why this skill exists and what problem it solves
  ## When to invoke   — the exact situations this skill applies
  ## Steps            — numbered list of what to do
  ## Checklist        — if the skill is a checklist, the items (optional)
  ## Examples         — 1-2 concrete examples (optional)
  ## Notes            — caveats, edge cases, known limitations (optional)

Respond ONLY with the complete SKILL.md content, starting with ---
No preamble. No code fences.
"""


def _strip_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
        if text.endswith("```"):
            text = text.rsplit("```", 1)[0]
        if text.startswith("markdown"):
            text = text[8:]
    return text.strip()


def _call_llm(client: Any, system: str, user: str) -> str:
    for attempt in range(3):
        try:
            return _strip_fences(client.generate(system, user, MAX_TOKENS))
        except Exception as e:
            if attempt < 2:
                time.sleep(2 ** attempt)
            else:
                return f"# Skill generation failed\n\nError: {e}\n"
    return "# Skill generation failed\n"


def _git(cwd: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + list(args),
        cwd=cwd, capture_output=True, text=True, check=check,
    )


def _gh(*args: str, check: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["gh"] + list(args),
        capture_output=True, text=True, check=check,
    )


def _infer_repo_from_remote() -> str | None:
    try:
        r = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, timeout=5,
        )
        if r.returncode != 0:
            return None
        url = r.stdout.strip()
        for prefix in ("git@github.com:", "https://github.com/", "http://github.com/"):
            if url.startswith(prefix):
                slug = url[len(prefix):].removesuffix(".git")
                if "/" in slug:
                    return slug
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Issue creation (soft-fail)
# ---------------------------------------------------------------------------

def _create_tracking_issue(target_repo: str, skill_items: list[dict]) -> str | None:
    """Create a GitHub issue listing the skills to be implemented. Soft-fail."""
    titles = "\n".join(f"- [ ] `{i.get('skill_name', i['id'])}` — {i['title']}" for i in skill_items)
    body = textwrap.dedent(f"""\
        tricorder improve identified {len(skill_items)} recommendations that can be
        implemented as agent skills.

        ## Skills to implement

        {titles}

        ---
        *Generated by [tricorder](https://github.com/dhk/tricorder) improve --forge*
    """)

    result = _gh(
        "issue", "create",
        "--repo", target_repo,
        "--title", f"tricorder: implement {len(skill_items)} review skills",
        "--body", body,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    return None


# ---------------------------------------------------------------------------
# Skill generation (background thread)
# ---------------------------------------------------------------------------

def _generate_skills_background(
    client: Any,
    skill_items: list[dict],
    work_dir: str,
    results: dict,
) -> None:
    """Generate SKILL.md content for each item. Runs in a background thread."""
    for item in skill_items:
        name = item.get("skill_name") or item["id"].lower()
        user_prompt = textwrap.dedent(f"""\
            Skill name: {name}
            Trigger: {item.get('skill_trigger', 'when reviewing code')}
            Description: {item.get('skill_description', item['title'])}

            Full context:
            {item.get('description', '')}

            Evidence from review record:
            {item.get('evidence', '(none provided)')}

            Standard citation:
            {item.get('standard_citation') or '(none)'}

            Category: {item.get('category', 'skill')}
            Impact: {item.get('impact', 'medium')}
        """)

        content = _call_llm(client, SYSTEM_SKILL, user_prompt)
        results[name] = content

        skill_dir = Path(work_dir) / "skills" / name
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(content)

        print(f"  ✓ skills/{name}/SKILL.md")


# ---------------------------------------------------------------------------
# Main forge runner
# ---------------------------------------------------------------------------

def run_forge(skill_items: list[dict], tri_dir: Path, source_repo: str) -> None:
    from tricorder.llm import build_llm_provider

    print()
    print("Skills Forge")
    print("=" * 40)
    print()

    # Ask for target repo
    inferred = _infer_repo_from_remote()
    try:
        if inferred:
            answer = input(f"Target repo for skills [{inferred}]: ").strip()
            target_repo = answer or inferred
        else:
            target_repo = input("Target repo for skills (OWNER/REPO): ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        return

    if not target_repo or "/" not in target_repo:
        print("Invalid repo. Skills forge aborted.")
        return

    # Verify gh is available and authenticated
    gh_check = _gh("auth", "status")
    if gh_check.returncode != 0:
        print("gh CLI not authenticated. Run `gh auth login` first.")
        print("Skills forge aborted.")
        return

    client = build_llm_provider()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    branch = f"feat/tricorder-skills-{today}"

    print(f"  Repo:    {target_repo}")
    print(f"  Branch:  {branch}")
    print(f"  Skills:  {len(skill_items)}")
    print()

    # Create tracking issue (soft-fail)
    print("Creating tracking issue …", end=" ", flush=True)
    issue_url = _create_tracking_issue(target_repo, skill_items)
    if issue_url:
        print(f"✓ {issue_url}")
    else:
        print("(skipped — repo may not exist or gh lacks write access)")
    print()

    # Clone target repo
    tmp = tempfile.mkdtemp(prefix="tricorder-forge-")
    try:
        print(f"Cloning {target_repo} …", end=" ", flush=True)
        clone = subprocess.run(
            ["gh", "repo", "clone", target_repo, tmp, "--", "--depth=1"],
            capture_output=True, text=True,
        )
        if clone.returncode != 0:
            print(f"Clone failed: {clone.stderr.strip()}")
            print("Skills forge aborted.")
            return
        print("✓")

        # Create branch
        _git(tmp, "checkout", "-b", branch)

        # Generate skills in a background thread, stream progress to stdout
        print()
        print(f"Generating {len(skill_items)} skills …")
        results: dict[str, str] = {}
        thread = threading.Thread(
            target=_generate_skills_background,
            args=(client, skill_items, tmp, results),
            daemon=True,
        )
        thread.start()
        thread.join()  # wait for all skills before committing

        if not results:
            print("No skills generated. Forge aborted.")
            return

        # Also write a tricorder-generated README in skills/
        skills_root = Path(tmp) / "skills"
        if skills_root.exists():
            readme = _render_skills_readme(skill_items, source_repo, today)
            (skills_root / "README.md").write_text(readme)

        # Stage everything
        _git(tmp, "add", "skills/")

        # Commit
        commit_msg = (
            f"feat: add {len(results)} tricorder-generated review skills\n\n"
            f"Skills generated by tricorder improve from {source_repo or 'review analysis'}.\n"
            f"Each skill captures a recurring review pattern as an agent-invokable checklist.\n\n"
            + (f"Tracking issue: {issue_url}\n" if issue_url else "")
            + f"\nCo-Authored-By: tricorder <noreply@github.com>"
        )

        commit = _git(tmp, "commit", "-m", commit_msg, check=False)
        if commit.returncode != 0:
            # Nothing to commit (all skills dirs existed)
            if "nothing to commit" in commit.stdout or "nothing to commit" in commit.stderr:
                print("Nothing new to commit — skills already exist on this branch.")
            else:
                print(f"Commit failed: {commit.stderr.strip()}")
            return

        # Push
        print()
        print(f"Pushing branch {branch} …", end=" ", flush=True)
        push = subprocess.run(
            ["gh", "repo", "fork", "--clone=false"],  # no-op if already forked
            cwd=tmp, capture_output=True,
        )
        push = _git(tmp, "push", "--set-upstream", "origin", branch, check=False)
        if push.returncode != 0:
            print(f"Push failed: {push.stderr.strip()}")
            return
        print("✓")

        # Create PR
        print("Creating pull request …", end=" ", flush=True)
        pr_body = _render_pr_body(skill_items, source_repo, issue_url)
        pr = subprocess.run(
            [
                "gh", "pr", "create",
                "--repo", target_repo,
                "--head", branch,
                "--title", f"feat: {len(results)} tricorder review skills",
                "--body", pr_body,
            ],
            cwd=tmp, capture_output=True, text=True,
        )
        if pr.returncode == 0:
            pr_url = pr.stdout.strip()
            print(f"✓")
            print()
            print(f"  PR:  {pr_url}")
        else:
            print(f"(PR creation failed: {pr.stderr.strip()[:120]})")
            print(f"Branch {branch} is pushed — create the PR manually.")

    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print()
    print("Skills Forge complete.")
    print()


# ---------------------------------------------------------------------------
# Rendered content helpers
# ---------------------------------------------------------------------------

def _render_skills_readme(items: list[dict], source_repo: str, today: str) -> str:
    lines = [
        "# Review Skills",
        "",
        f"*Generated {today} by [tricorder improve](https://github.com/dhk/tricorder)*",
        f"*Source analysis: {source_repo or 'review history'}*",
        "",
        "These skills capture recurring patterns from code review history.",
        "Each skill is a SKILL.md file that can be invoked by an AI assistant",
        "during code review or authoring.",
        "",
        "## Skills in this directory",
        "",
        "| Skill | Description | Category | Impact |",
        "|-------|-------------|----------|--------|",
    ]
    for item in items:
        name = item.get("skill_name") or item["id"].lower()
        desc = item.get("skill_description") or item.get("title", "")
        lines.append(
            f"| [{name}]({name}/SKILL.md) | {desc} "
            f"| {item.get('category','')} | {item.get('impact','')} |"
        )
    lines += [
        "",
        "---",
        "",
        "To update these skills, re-run `tricorder improve --forge` on an updated analysis.",
    ]
    return "\n".join(lines)


def _render_pr_body(items: list[dict], source_repo: str, issue_url: str | None) -> str:
    skill_list = "\n".join(
        f"- `skills/{i.get('skill_name') or i['id'].lower()}/SKILL.md` — {i['title']}"
        for i in items
    )
    issue_line = f"\nCloses {issue_url}\n" if issue_url else ""
    return textwrap.dedent(f"""\
        ## Summary

        Adds {len(items)} agent skills generated by `tricorder improve` from review history analysis of `{source_repo or 'the repository'}`.

        Each skill captures a recurring pattern from the PR review record as a reusable SKILL.md that an AI assistant can invoke during code review or authoring.

        ## Skills added

        {skill_list}

        ## How these were generated

        1. `tricorder analyze` — fetched PR review data from GitHub
        2. `tricorder learn` — extracted patterns via LLM (4-phase pipeline)
        3. `tricorder improve` — synthesized a prioritized improvement roadmap
        4. `tricorder improve --forge` — generated these SKILL.md files from skill-shaped roadmap items
        {issue_line}
        ## Review notes

        - Each skill has a trigger phrase list — these are the phrases that cause an AI assistant to invoke the skill
        - Skills are intentionally narrow in scope; a skill should do one thing well
        - Edit the `## Checklist` sections to match your team's specific standards
        - Promote to CI enforcement by extracting rules into SQLFluff / linters as the team validates them

        ---
        🤖 Generated with [tricorder](https://github.com/dhk/tricorder)
    """)
