// tricorder — explorer data
// Generated by tricorder-render-explorer.py on 2026-06-03 19:17
// Version: 1.0.0.1  |  Repo: cal-itp/data-infra  |  Window: 2026-03-02 → 2026-05-30
// Names anonymized: yes
window.TRICORDER_DATA = (function () {

  const CATEGORIES = ["grain", "naming", "testing", "documentation", "style", "performance", "modeling", "schema", "business-logic"];
  const RADAR_CATEGORIES = CATEGORIES;
  const CATEGORY_GROUP = {"grain": "data", "naming": "pattern", "testing": "tool", "documentation": "pattern", "style": "pattern", "performance": "data", "modeling": "data", "schema": "data", "business-logic": "pattern"};

  const patterns = [
  {
    "signal": "Unit tests cited as primary validation evidence for infrastructure/pipeline code rather than integration or end-to-end tests",
    "category": "test-pyramid",
    "maturity": "judgment",
    "standard_citation": "The Checklist Manifesto \u2014 checklist-worthy: confirm test pyramid coverage (unit + integration + e2e) before merging data-critical pipeline code",
    "reviewer": "Scott",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "there are tests for everything, the 5 core modules."
      },
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "I understand parts of this"
      }
    ]
  },
  {
    "signal": "Proof-of-concept framing used to defer formal migration plan and reliability benchmarking for a data-critical feed",
    "category": "other",
    "maturity": "judgment",
    "standard_citation": null,
    "reviewer": "evansiroky",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "I had a chat with @O'Brien about this and got clarification that these are proofs-of-concepts that will be part of a recommendation on how to proceed."
      },
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "Given the importance of reliably collecting RT data, I would like for there to be a more formal migration plan setup that includes at least 2 weeks of testing"
      }
    ]
  },
  {
    "signal": "Terraform plan used as the sole pre-merge testing artifact for infrastructure changes",
    "category": "other",
    "maturity": "guidance",
    "standard_citation": null,
    "reviewer": "Scott",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "How has this been tested? `terraform plan`"
      }
    ]
  },
  {
    "signal": "Reliability concerns raised for real-time data archiving pipeline were resolved via conversation rather than documented requirements or formal SLA definition",
    "category": "documentation",
    "maturity": "guidance",
    "standard_citation": null,
    "reviewer": "evansiroky",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "I had a chat with @O'Brien about this and got clarification"
      },
      {
        "pr": "#4491",
        "date": "2026-04-21",
        "author": "O'Brien",
        "quote": "Given the importance of reliably collecting RT data, I would like for there to be a more formal migration plan"
      }
    ]
  },
  {
    "signal": "DAG fan-out reduction via workflow unification improves pipeline maintainability",
    "category": "modeling",
    "maturity": "judgment",
    "standard_citation": "Kimball dimensional modeling \u2014 avoid redundant processing paths that inflate lineage complexity",
    "reviewer": "LaForge",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "Analysts see a fanned-out DAG for processing Littlepay files"
      },
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "This PR unifies and adds test coverage for the Littlepay sync and parse workflow"
      }
    ]
  },
  {
    "signal": "Breaking changes bundled with test coverage additions require explicit migration communication",
    "category": "other",
    "maturity": "guidance",
    "standard_citation": null,
    "reviewer": "LaForge",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "Breaking change (fix or feature that would cause existing functionality to not work as expected)"
      },
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "This PR unifies and adds test coverage for the Littlepay sync and parse workflow"
      }
    ]
  },
  {
    "signal": "Post-merge monitoring step called out explicitly for staging validation before production confidence",
    "category": "other",
    "maturity": "convention",
    "standard_citation": "The Checklist Manifesto \u2014 post-merge monitoring is a checklist-worthy step for breaking changes",
    "reviewer": "LaForge",
    "author": "O'Brien",
    "evidence": [
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "Monitor execution on staging"
      },
      {
        "pr": "#4537",
        "date": "2026-04-15",
        "author": "O'Brien",
        "quote": "Actions required (specified below)"
      }
    ]
  },
  {
    "signal": "Infrastructure bucket naming convention corrected to match environment-prefixed standard (calitp-staging-* vs cal-itp-data-infra-*)",
    "category": "naming",
    "maturity": "rule",
    "standard_citation": "dbt Labs style guide: consistent environment and resource naming conventions",
    "reviewer": "Sulu",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4673",
        "date": "2026-04-08",
        "author": "LaForge",
        "quote": "replaces references to `cal-itp-data-infra-enghouse-raw` and `cal-itp-data-infra-staging-enghouse-raw` by `calitp-staging-enghouse-raw` bucket with the correct name convention on Staging"
      }
    ]
  },
  {
    "signal": "Bug fix validated via infrastructure plan (Terraform plan) rather than data pipeline execution, appropriate for infrastructure naming changes",
    "category": "other",
    "maturity": "guidance",
    "standard_citation": "The Checklist Manifesto: verification method should match the type of change being made",
    "reviewer": "Sulu",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4673",
        "date": "2026-04-08",
        "author": "LaForge",
        "quote": "Tested with `Terraform plan`."
      }
    ]
  },
  {
    "signal": "Change is part of a multi-PR series (#4672, #4760, #4673) suggesting a naming convention remediation effort split across iterations",
    "category": "naming",
    "maturity": "judgment",
    "standard_citation": null,
    "reviewer": "Sulu",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4673",
        "date": "2026-04-08",
        "author": "LaForge",
        "quote": "Continuation of PR #4672 and #4760."
      }
    ]
  },
  {
    "signal": "Multi-PR sequencing with explicit merge-order dependency documented in PR description",
    "category": "other",
    "maturity": "convention",
    "standard_citation": null,
    "reviewer": "Rand",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4759",
        "date": "2026-05-07",
        "author": "LaForge",
        "quote": "This is the last PR from a sequence of #4672 and #4673 in order to correct the bucket name."
      },
      {
        "pr": "#4759",
        "date": "2026-05-07",
        "author": "LaForge",
        "quote": "PR #4673 need to be merged first!"
      }
    ]
  },
  {
    "signal": "Alert window and evaluation period explicitly documented in PR description",
    "category": "documentation",
    "maturity": "convention",
    "standard_citation": null,
    "reviewer": null,
    "author": "Chekov",
    "evidence": [
      {
        "pr": "#4856",
        "date": "2026-03-02",
        "author": "Chekov",
        "quote": "every 5 mins, checking the total writes between 5 mins ago and 10 mins ago. if the count stays below 5000 for 2 mins, trigger the alert."
      }
    ]
  },
  {
    "signal": "Incremental model required --full-refresh after schema change (new array columns added)",
    "category": "incremental",
    "maturity": "rule",
    "standard_citation": "dbt incremental model docs: adding columns to an incremental model requires --full-refresh or on_schema_change config",
    "reviewer": null,
    "author": "Crusher",
    "evidence": [
      {
        "pr": "#4857",
        "date": "2026-03-02",
        "author": "Crusher",
        "quote": "`poetry run dbt run -s fct_trip_updates_trip_metrics --full-refresh` (incremental, columns added)"
      }
    ]
  },
  {
    "signal": "New behavior covered by pytest to validate empty-file handling path",
    "category": "testing",
    "maturity": "convention",
    "standard_citation": "The Checklist Manifesto \u2014 new code paths require corresponding test coverage",
    "reviewer": "O'Brien",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4858",
        "date": "2026-03-04",
        "author": "LaForge",
        "quote": "Tested locally creating a new pytest."
      }
    ]
  },
  {
    "signal": "Join fanout caused by missing composite key dimension (feed_version omitted from join predicate)",
    "category": "grain",
    "maturity": "rule",
    "standard_citation": "Kimball dimensional modeling: all join keys must fully identify grain of the dimension table",
    "reviewer": "O'Brien",
    "author": "Spock",
    "evidence": [
      {
        "pr": "#4860",
        "date": "2026-03-03",
        "author": "Spock",
        "quote": "This PR adds `feed_version` to a couple of joins to address issue #4811. The issue was caused because there some instances where the same product_id appears in both the v1 and v3 data feeds for an agency, which was causing fanout."
      }
    ]
  },
  {
    "signal": "Merge conflict present at approval time \u2014 reviewer approved despite known conflict",
    "category": "other",
    "maturity": "rule",
    "standard_citation": "Standard VCS practice \u2014 PRs should be conflict-free before approval",
    "reviewer": "Scott",
    "author": "Spock",
    "evidence": [
      {
        "pr": "#4863",
        "date": "2026-03-04",
        "author": "Spock",
        "quote": "Though there is some merge conflict going on."
      }
    ]
  },
  {
    "signal": "Casting a zero-padded string code to INT64 collapses semantically distinct values (e.g., '000' vs '0'); type must preserve leading zeros",
    "category": "schema",
    "maturity": "deterministic",
    "standard_citation": "SQLFluff / dbt type fidelity: identifier-like codes should remain STRING",
    "reviewer": null,
    "author": "Rand",
    "evidence": [
      {
        "pr": "#5284",
        "date": "2026-05-13",
        "author": "Rand",
        "quote": "Fix terminal_spdh_code type from INT64 back to string (INT64 cast was collapsing '000' and '0' into the same value; string preserves the distinction)"
      }
    ]
  },
  {
    "signal": "YAML model patch names must exactly match the SQL model file names to avoid 'Did not find matching node for patch' warnings",
    "category": "naming",
    "maturity": "deterministic",
    "standard_citation": "dbt Labs \u2014 schema YAML patch name must match model name exactly",
    "reviewer": "Scott",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#4941",
        "date": "2026-03-16",
        "author": "LaForge",
        "quote": "[WARNING]: Did not find matching node for patch with name 'int_gtfs_rt__vehicle_positions_trip_stop_day_map_grouping_orig' in the 'models' section"
      }
    ]
  },
  {
    "signal": "Elavon customer name casing corrected to all-caps to match vendor-delivered format, preventing silent join failures",
    "category": "business-logic",
    "maturity": "deterministic",
    "standard_citation": null,
    "reviewer": null,
    "author": "Rand",
    "evidence": [
      {
        "pr": "#5284",
        "date": "2026-05-13",
        "author": "Rand",
        "quote": "Fixes Ventura elavon_customer_name to match the all-caps format as delivered by Elavon"
      }
    ]
  },
  {
    "signal": "Environment variable file contained a copy-paste typo (wrong bucket name in .development.env)",
    "category": "other",
    "maturity": "deterministic",
    "standard_citation": "The Checklist Manifesto: environment config files are checklist-worthy; verify all references match intended environment/resource names",
    "reviewer": "Scott",
    "author": "LaForge",
    "evidence": [
      {
        "pr": "#5313",
        "date": "2026-05-15",
        "author": "LaForge",
        "quote": "Typo? staging bucket instead?"
      }
    ]
  }
];

  const reviewers = [
  {
    "login": "Spock",
    "review_style": "thorough",
    "signal_quality": "high",
    "primary_focus_areas": [
      {
        "area": "Incremental model strategy correctness, specifically requiring microbatch incremental strategy for models partitioned on `dt` and use of ranged-date macros for non-partitioned upstream sources",
        "frequency": "often"
      },
      {
        "area": "Correct use of `source_record_id` vs. `key` (versioned identifier) for persistent/stable lookups in seeds and joins",
        "frequency": "often"
      },
      {
        "area": "Correctness of deduplication logic, especially preventing inappropriate cross-feed deduplication and ensuring deduplication is scoped to the right grain",
        "frequency": "often"
      },
      {
        "area": "Proper use of dbt exposures for published/externally-surfaced models rather than ad-hoc meta tags",
        "frequency": "often"
      },
      {
        "area": "Accuracy of documentation about when DAGs/jobs need to re-run, specifically around external table creation (clarifying it only needs to run on schema/path changes, not for new data)",
        "frequency": "often"
      },
      {
        "area": "SCD Type 2 correctness: joining dimension tables using valid_to/valid_from date ranges aligned to the fact's `dt` rather than an `_is_current` flag",
        "frequency": "sometimes"
      },
      {
        "area": "CI/CD workflow correctness and job dependency ordering (needs, artifact timing, Terraform plan scenarios)",
        "frequency": "sometimes"
      },
      {
        "area": "Documentation completeness and clarity: linking to prerequisite steps, clarifying ambiguous instructions, flagging broken/unresolved references",
        "frequency": "often"
      },
      {
        "area": "Row access policy / security macro application correctness and completeness for new models",
        "frequency": "sometimes"
      },
      {
        "area": "Query refactoring suggestions for clarity or idiomatic SQL/dbt (e.g., QUALIFY clause, CTE pre-filtering before joins)",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "Test coverage: adding or requiring dbt schema tests (uniqueness, not_null, referential integrity) on new models or columns",
        "basis": "Across 40 PRs including multiple new mart models (fct_tides_vehicle_locations, fct_tides_trips_performed, fct_payment_rides additions), there are no comments requesting or questioning the presence of dbt tests in .yml files."
      },
      {
        "area": "Column-level documentation in .yml files (descriptions for new columns/models)",
        "basis": "No comments observed requesting column descriptions or model descriptions be added to schema YAML files despite multiple new models being introduced."
      },
      {
        "area": "Performance/cost considerations for BigQuery scans (e.g., partition pruning, clustering key selection on new models)",
        "basis": "Despite reviewing incremental model patterns closely, there are no comments about partition or clustering key choices on new fact models to control scan cost."
      },
      {
        "area": "Naming conventions for models and columns (prefix conventions like stg_/int_/fct_/dim_)",
        "basis": "No comments observed enforcing or questioning model naming conventions across any of the 40 reviewed PRs."
      }
    ],
    "category_freq": {
      "grain": 70,
      "naming": 45,
      "testing": 8,
      "documentation": 70,
      "style": 45,
      "performance": 8,
      "modeling": 70,
      "schema": 70,
      "business-logic": 70
    }
  },
  {
    "login": "Data",
    "review_style": "conversational",
    "signal_quality": "medium",
    "primary_focus_areas": [
      {
        "area": "Deduplication logic correctness \u2014 partition key granularity, ordering column choice, and placement of dedup CTEs",
        "frequency": "always"
      },
      {
        "area": "Fact table grain integrity \u2014 ensuring non-degenerate dimensions are not included in fact tables and that fan-out collapses are scoped correctly",
        "frequency": "always"
      },
      {
        "area": "Spec-conformance of derived fields \u2014 validating that conditional logic for foreign keys aligns with upstream spec semantics (e.g., GTFS-RT schedule_relationship values)",
        "frequency": "often"
      },
      {
        "area": "dbt exposure definitions \u2014 using exposures rather than ad-hoc meta blocks for downstream publish/product references, and coordinating cross-model ref() resolution in the same PR",
        "frequency": "often"
      },
      {
        "area": "SCD Type 2 join correctness \u2014 time-window predicate scope and CTE structure for historical correctness",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "Model testing coverage \u2014 no comments observed about missing or insufficient dbt tests (unique, not_null, accepted_values, relationships) on new fact models",
        "basis": "Across 3 PRs introducing new fct_ models, no review comments address test declarations in .yml files despite this being a standard dbt quality gate"
      },
      {
        "area": "Documentation completeness \u2014 column-level descriptions in .yml files not surfaced as a concern",
        "basis": "Comments on _mart_tides.yml focused exclusively on exposure structure, with no mention of missing or incomplete column descriptions for new fact table columns"
      },
      {
        "area": "Incremental strategy configuration \u2014 no review comments about materialization choice or incremental_strategy for large fact tables",
        "basis": "fct_ models in a mart layer would typically warrant discussion of incremental vs. table materialization; no such comments appear in any reviewed PR"
      }
    ],
    "category_freq": {
      "grain": 90,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 90,
      "performance": 8,
      "modeling": 70,
      "schema": 70,
      "business-logic": 70
    }
  },
  {
    "login": "Troi",
    "review_style": "advisory",
    "signal_quality": "medium",
    "primary_focus_areas": [
      {
        "area": "Documentation completeness and accuracy for domain processes (onboarding guides, workflow runbooks, tutorials)",
        "frequency": "often"
      },
      {
        "area": "Specificity in documentation references \u2014 pointing to exact table/column names rather than vague references",
        "frequency": "sometimes"
      },
      {
        "area": "Suppressing irrelevant or unused fields from mart/staging tables to reduce noise for end users",
        "frequency": "sometimes"
      },
      {
        "area": "Definition of done / completion criteria for process templates and onboarding tickets",
        "frequency": "sometimes"
      },
      {
        "area": "Diagram/rendered artifact correctness (e.g. Mermaid syntax validation)",
        "frequency": "sometimes"
      },
      {
        "area": "Downstream data lineage / business logic understanding \u2014 asking clarifying questions about how upstream changes propagate",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL model grain declaration and primary key testing",
        "basis": "Across multiple PRs touching dbt models (fct_payments_aggregations, stg_littlepay, mart tables), no comments address whether grain is documented, uniqueness tests are defined, or whether existing unique test failures are triaged systematically \u2014 the one mention of unique test failures is a passing question deferred to another reviewer."
      },
      {
        "area": "dbt model structure conventions (staging vs. intermediate vs. mart layer separation, naming conventions)",
        "basis": "No comments across any PR reference dbt best practices around model layering, naming, or ref usage despite reviewing multiple mart and staging model PRs."
      },
      {
        "area": "SQL code quality (CTEs, readability, filter placement, join correctness)",
        "basis": "No inline comments on SQL logic, query structure, or correctness in any of the model PRs reviewed; reviews of data model PRs are almost entirely approvals with business-level clarifying questions."
      },
      {
        "area": "Test coverage gaps (missing not_null, accepted_values, relationship tests)",
        "basis": "No comments request additional dbt schema tests on any reviewed PR despite several touching _payments.yml schema files."
      },
      {
        "area": "Infrastructure/environment configuration review",
        "basis": "PR #5350 (adding a Composer env variable) received a bare approval with no comment, suggesting low engagement with infrastructure-level changes."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 70,
      "style": 8,
      "performance": 8,
      "modeling": 45,
      "schema": 8,
      "business-logic": 70
    }
  },
  {
    "login": "Bashir",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [],
    "apparent_blind_spots": [
      {
        "area": "Cannot identify blind spots with only one approved PR and no inline comments",
        "basis": "Single PR review with no substantive comments makes it impossible to characterize what the reviewer overlooks"
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Chekov",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Security vulnerability awareness, particularly for dependency pins that introduce or retain known CVEs",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL/dbt model correctness, grain, lineage, and testing",
        "basis": "None of the 5 reviewed PRs contain any dbt/SQL-specific feedback; no comments on model grain, ref() usage, source freshness, schema tests, or documentation \u2014 though the repo is a dbt/SQL analytics repo where such concerns are common."
      },
      {
        "area": "Code logic and implementation detail review",
        "basis": "Four of five approvals contain no substantive commentary at all, suggesting the reviewer rarely scrutinizes the actual change logic, configuration values, or edge cases."
      },
      {
        "area": "Infrastructure/Kubernetes configuration correctness",
        "basis": "PR #5333 scaled node pool floors to 0 \u2014 a potentially impactful infra change \u2014 with only 'looks good', indicating no visible scrutiny of resource implications or rollback risk."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Crusher",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Sanity-checking incremental/microbatch strategy outputs against existing production models",
        "frequency": "sometimes"
      },
      {
        "area": "Tooling and environment changes (poetry \u2192 uv migration, JupyterHub image updates)",
        "frequency": "sometimes"
      },
      {
        "area": "Acknowledging and approving incremental model simplifications",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL logic correctness and model grain declaration",
        "basis": "No comments across any PR inspect SQL logic, joins, aggregation correctness, or grain definitions on fact/dim models despite several dbt model PRs being reviewed."
      },
      {
        "area": "Schema/column-level changes and data type validation",
        "basis": "No comments reference schema files, column definitions, accepted values tests, or data type mismatches across any of the reviewed PRs."
      },
      {
        "area": "dbt testing coverage (generic or singular tests)",
        "basis": "No comments mention whether new or modified models have associated dbt tests (not_null, unique, relationships, etc.)."
      },
      {
        "area": "Code review of non-infrastructure PRs (Airtable automation, HubSpot email, CODEOWNERS)",
        "basis": "PRs #5045, #5297, and #5302 received bare approvals with no substantive commentary, suggesting limited scrutiny of logic in those domains."
      },
      {
        "area": "Performance considerations for large incremental models (partitioning, clustering, look-back windows)",
        "basis": "Despite reviewing multiple microbatch/incremental PRs, no comments address BigQuery partition pruning, clustering keys, or incremental predicates."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 45,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "LaForge",
    "review_style": "conversational",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "DAG task dependency structure and flow correctness in Airflow pipelines",
        "frequency": "sometimes"
      },
      {
        "area": "CI/CD workflow job naming and dependency correctness (GitHub Actions)",
        "frequency": "sometimes"
      },
      {
        "area": "GCP credentials and secrets configuration in workflows",
        "frequency": "sometimes"
      },
      {
        "area": "Model/table placement correctness (mart vs intermediate vs staging) relative to exposure and Metabase access",
        "frequency": "sometimes"
      },
      {
        "area": "YAML documentation completeness for new or renamed dbt models",
        "frequency": "sometimes"
      },
      {
        "area": "Reusability of Airflow operators vs one-off implementations",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL model grain declaration and fanout/duplication risks",
        "basis": "No comments across 41 PRs touching dbt SQL models about grain, surrogate keys, or row-level duplication, despite multiple dbt model PRs being reviewed."
      },
      {
        "area": "dbt test coverage (schema tests, uniqueness, not-null, referential integrity)",
        "basis": "Only one passing mention of tests being re-enabled (#5036) with no substantive critique of test coverage gaps in any other PR."
      },
      {
        "area": "Incremental model strategy correctness (unique_key, partition logic, lookback windows)",
        "basis": "PR #4926 introduced a microbatch incremental strategy and PR #4932 added a lookback days variable, but reviewer comments focused on table comparison logistics rather than correctness of the incremental logic itself."
      },
      {
        "area": "Performance and cost implications of BigQuery model materialization choices",
        "basis": "Reviewer acknowledged in #5318 'we need to optimize these new tables but lets merge and test it' \u2014 optimization concerns are deferred rather than raised as blockers."
      },
      {
        "area": "Terraform resource naming conventions and module structure",
        "basis": "Multiple Terraform PRs (#5025, #5033, #5306, #5313, #5351) were approved with minimal or no inline commentary on resource naming, tagging, or module hygiene."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 45,
      "testing": 8,
      "documentation": 45,
      "style": 8,
      "performance": 8,
      "modeling": 45,
      "schema": 45,
      "business-logic": 8
    }
  },
  {
    "login": "O'Brien",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Pairing and collaborative review acknowledgment \u2014 frequently notes pair programming sessions as part of approval context",
        "frequency": "sometimes"
      },
      {
        "area": "Approving infrastructure and workflow changes (Terraform, Kubernetes, GCP IAM, GitHub Actions workflows) without detailed blocking comments",
        "frequency": "always"
      },
      {
        "area": "Approving data pipeline and ETL changes (Littlepay sync, GTFS processing, Airflow DAGs) with minimal friction",
        "frequency": "always"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "dbt model grain declaration and primary key documentation",
        "basis": "No review comments visible across any of the 24 PRs touching dbt models (e.g., PR #5273 deploy-dbt workflow, PR #5106) that mention grain, uniqueness tests, or primary key constraints \u2014 standard dbt best practices per dbt Labs style guide."
      },
      {
        "area": "SQL correctness and join logic scrutiny",
        "basis": "PR #4860 explicitly fixes a deduplication bug via adding feed_version to joins, yet the approval is uncommented \u2014 suggesting join correctness and fanout risks are not areas O'Brien actively interrogates in review."
      },
      {
        "area": "Test coverage for dbt models (schema.yml uniqueness/not_null tests)",
        "basis": "None of the 24 approvals contain any comment requesting or acknowledging dbt schema tests, despite multiple PRs touching dbt models and audit tables."
      },
      {
        "area": "False positive / alerting threshold rationale documentation",
        "basis": "PRs #4856 and #4888 both tune alert thresholds and are approved with no inline questions about threshold justification, rollback plans, or documentation of the chosen values."
      },
      {
        "area": "Security review depth on IAM permission changes",
        "basis": "PR #5262 downgrades IAM permissions and is approved without any visible commentary on principle of least privilege validation or blast radius assessment."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 90,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 90
    }
  },
  {
    "login": "Rand",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Documentation accuracy and rendering correctness in runbooks/workflow docs",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL logic correctness and grain validation in fact/transaction models",
        "basis": "PRs #5206 and #5212 add Enghouse agencies to Elavon and fct_payments models with only 'LGTM' approval \u2014 no inline comments on join logic, grain, or filter correctness"
      },
      {
        "area": "dbt model configuration (materialization, incremental strategy, unique_key)",
        "basis": "PR #5223 re-adds a full_refresh tag post-migration with no scrutiny of whether the strategy or model config is appropriate"
      },
      {
        "area": "Warehouse migration correctness (schema, table naming, data pipeline impact)",
        "basis": "PR #4828 moves reconciliation tables into the warehouse with only a complimentary approval and no inline review of table definitions or downstream dependencies"
      },
      {
        "area": "Bucket name correctness and environment-specific config validation",
        "basis": "PR #4759 corrects a production bucket name \u2014 a high-risk change \u2014 approved with only 'LGTM' and no verification comments"
      },
      {
        "area": "Referential integrity and upstream/downstream model impact analysis",
        "basis": "No comments across any PR reference lineage checks, ref() usage, or impact on dependent models"
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 45,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Ro",
    "review_style": "conversational",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "CI/CD workflow configuration and dbt-metabase CLI flag compatibility",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "SQL model logic, grain declarations, and dbt model design patterns",
        "basis": "Only one PR reviewed and the single comment is entirely about a GitHub Actions workflow YAML file and a CLI tool's flag support \u2014 no evidence of engagement with SQL, model structure, documentation, or dbt best practices."
      },
      {
        "area": "Test coverage and schema contracts (dbt tests, sources, contracts)",
        "basis": "No comments touching on dbt testing, schema.yml definitions, or data contract enforcement across the single observed review."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Scott",
    "review_style": "conversational",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Pre-approving or approving PRs without hands-on testing, often explicitly noting they haven't run the code",
        "frequency": "always"
      },
      {
        "area": "Operational/infrastructure safety \u2014 ensuring paused jobs, staged rollouts, or non-destructive changes before merging",
        "frequency": "often"
      },
      {
        "area": "Merge conflicts and CI check status as a gate before merging",
        "frequency": "often"
      },
      {
        "area": "Correctness of test fixtures and test data matching production paths/values",
        "frequency": "sometimes"
      },
      {
        "area": "Cost risk from unbounded queries or expensive BigQuery views exposed to BI tools",
        "frequency": "sometimes"
      },
      {
        "area": "README and documentation accuracy (schedules, paths, descriptions matching implementation)",
        "frequency": "sometimes"
      },
      {
        "area": "GitHub issue lifecycle hygiene \u2014 avoiding auto-close of issues via keyword misuse",
        "frequency": "sometimes"
      },
      {
        "area": "Infrastructure environment targeting \u2014 ensuring staging vs production environment correctness in Terraform",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "dbt model grain declaration and incremental model correctness (unique_key, event_time, full_refresh behavior)",
        "basis": "Multiple PRs migrate models to microbatch strategy with brief or no substantive review of dbt-specific configurations; Scott approves with comments like 'THERE'S A CHANGE A COMING' or 'We discussed this' without examining model SQL, grain, or unique_key definitions."
      },
      {
        "area": "SQL logic and transformation correctness",
        "basis": "No inline comments across any PR examine SELECT logic, joins, filters, or aggregations; reviews focus entirely on process, infrastructure, and metadata rather than what the SQL actually computes."
      },
      {
        "area": "Type annotations and return type correctness in Python operator code",
        "basis": "The one instance of catching a wrong return annotation (BigQueryToDictOperator) appears in a heavily commented PR (#5307) and was caught late among many comments, suggesting this is not a routine focus."
      },
      {
        "area": "dbt source and model YAML schema accuracy (field names, descriptions matching actual columns)",
        "basis": "In PR #5307 Scott notes '_src_tides.yml isn't right - some fields aren't matching' but dismisses it as 'not a big deal', indicating schema YAML correctness is underweighted."
      },
      {
        "area": "Security review of IAM permissions and service account scoping",
        "basis": "Multiple PRs add service accounts, IAM roles, and bucket permissions and receive one-line approvals with no scrutiny of least-privilege principles or permission scope."
      },
      {
        "area": "Unused imports and dead code in Python",
        "basis": "The unused import flag in PR #5307 was caught only in that single heavily-reviewed PR; no other Python PRs received this kind of static-analysis-level scrutiny."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 90,
      "documentation": 45,
      "style": 8,
      "performance": 45,
      "modeling": 45,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Sulu",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [],
    "apparent_blind_spots": [
      {
        "area": "No substantive review comments observed across any PR",
        "basis": "All 5 PRs were approved with no recorded comments, spanning naming conventions, Docker image updates, Airflow config, documentation, and dbt/SQL table creation \u2014 no feedback was given on any of them"
      },
      {
        "area": "SQL model design (grain declaration, surrogate keys, ref() usage)",
        "basis": "PR #5097 involves creating a Littlepay parse audit table \u2014 a meaningful schema change \u2014 yet no comments were recorded, suggesting SQL modeling standards are not being evaluated"
      },
      {
        "area": "Infrastructure and dependency changes (Docker images, Airflow variables)",
        "basis": "PRs #4900 and #5041 involve dependency version bumps and environment config with potential breaking-change risk; no scrutiny was applied"
      },
      {
        "area": "Naming conventions and dbt style guide adherence",
        "basis": "PR #4673 explicitly corrects a naming convention issue, yet no comment was left to confirm correctness or flag related issues elsewhere"
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Uhura",
    "review_style": "conversational",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "SQL readability and query logic simplification (e.g., preferring QUALIFY over array-based deduplication)",
        "frequency": "sometimes"
      },
      {
        "area": "Airflow DAG failure handling and alerting patterns (email_on_failure, on_failure_callback)",
        "frequency": "sometimes"
      },
      {
        "area": "Airflow task chaining and DAG structure to reduce repetition",
        "frequency": "sometimes"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "Model grain declaration and documentation on fact/mart models",
        "basis": "No comments across any PRs touching mart models (e.g., fct_create_expiring_gtfs_issues.sql) about declaring or validating grain, which is a common dbt review concern."
      },
      {
        "area": "Microbatch model configuration correctness (event_time, lookback, batch_size)",
        "basis": "Two PRs converting models to microbatch were approved without any recorded inline commentary on microbatch-specific configuration details, suggesting these were not scrutinized."
      },
      {
        "area": "Test coverage (dbt schema tests, uniqueness, not-null assertions)",
        "basis": "No comments across any PR about adding or verifying dbt tests on new or modified models."
      },
      {
        "area": "Idempotency and incremental model safety",
        "basis": "Microbatch and incremental model PRs were approved with no comments on whether logic is safe for reruns or late-arriving data."
      }
    ],
    "category_freq": {
      "grain": 45,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 45,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  },
  {
    "login": "Worf",
    "review_style": "advisory",
    "signal_quality": "low",
    "primary_focus_areas": [],
    "apparent_blind_spots": [
      {
        "area": "Unable to identify blind spots",
        "basis": "Only one PR reviewed with an approval and no recorded comments, providing insufficient signal to determine what the reviewer overlooks or underweights."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 8,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8
    }
  }
];

  const authors = [
  {
    "login": "Bashir",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Broad technical range across dbt, CI/CD, and infrastructure concerns \u2014 PRs span schema changes, linting, YAML syntax, CI pipeline optimization, and dependency management",
        "persistence": "consistent"
      },
      {
        "area": "Clean first-pass quality leading to quick approvals \u2014 majority of PRs approved with minimal revision cycles, indicating strong pre-submission review habits",
        "persistence": "consistent"
      },
      {
        "area": "Proactive maintenance work (deprecated syntax, test syntax migration yaml\u2192data_tests, dependency unpinning) \u2014 demonstrates ownership of codebase health beyond feature work",
        "persistence": "consistent"
      },
      {
        "area": "CI/CD pipeline improvements with measurable impact \u2014 PR #5162 (split dbt run/compile) produced visible performance gains noted by reviewers",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Anticipating all required arguments/parameters before review \u2014 PR #5095 required a follow-up round to add --vars argument support after reviewer pointed it out, suggesting the full requirements weren't fully scoped upfront",
        "persistence": "occasional",
        "support_recommendation": "Before submitting CI/infrastructure PRs, create a checklist of all user-facing arguments or configuration points that the feature should expose; review existing usage patterns or docs for the tool being wrapped to catch omissions before code review."
      },
      {
        "area": "Dependency scoping in CI jobs \u2014 PR #5162 required reviewer (LaForge) to flag that dbt-changed dependency was unnecessary on the compile job and should only be on the run job, indicating room to sharpen understanding of job dependency graphs",
        "persistence": "occasional",
        "support_recommendation": "When modifying CI workflow DAGs, draw or document the intended job dependency graph before implementation; have a second person review the graph logic specifically before the PR is opened, separate from code review."
      }
    ]
  },
  {
    "login": "Data",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Responsive and thorough in addressing reviewer feedback \u2014 consistently follows up inline with detailed explanations and fixes across multiple review rounds",
        "persistence": "consistent"
      },
      {
        "area": "Strong command of GTFS/GTFS-RT domain knowledge, accurately reasoning about spec semantics (e.g., trip_id, schedule_relationship) when challenged",
        "persistence": "consistent"
      },
      {
        "area": "Able to self-correct complex SQL logic (dedup partitioning, fan-out collapse, SCD Type 2 join patterns) once issues are surfaced by reviewers",
        "persistence": "consistent"
      },
      {
        "area": "Proactive documentation and metadata additions (exposures, YAML schema files) once reminded of team standards",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Incremental model strategy: consistently submits models without the correct incremental strategy for the warehouse pattern (microbatch for partitioned sources, ranged date macros for non-partitioned), requiring reviewer correction before approval",
        "persistence": "consistent",
        "support_recommendation": "Before starting any new incremental model, require Data to document in the PR description which upstream sources are involved, whether they are partitioned on dt, and which incremental strategy is therefore appropriate. Provide a one-page internal decision tree or checklist linking to the relevant warehouse PRs (e.g., #5092, #4837 issue) as a reference artifact."
      },
      {
        "area": "Deduplication logic scoping: dedup windows are initially too broad (across feeds rather than within a feed), losing valid data and conflating distinct logical entities",
        "persistence": "consistent",
        "support_recommendation": "During model design (before writing SQL), Data should explicitly write out the intended grain in a comment or PR description and confirm with a reviewer that the dedup partition columns match that grain. Add a team code-review checklist item: 'Does the ROW_NUMBER/dedup partition key fully identify the intended grain without collapsing across separate feeds or sources?'"
      },
      {
        "area": "Publishing/exposure metadata: initially uses non-standard meta tags (e.g., publish.product) instead of dbt exposures for published models, requiring reviewer redirection",
        "persistence": "consistent",
        "support_recommendation": "Add a standing PR template checklist item: 'If this model is published externally or feeds a data product, have you defined a dbt exposure in the relevant .yml file?' Link to an existing example exposure (e.g., california_open_data) in the template. Consider a brief async walkthrough of the exposure pattern with Data."
      },
      {
        "area": "Seed file versioning awareness: used a versioned identifier in a seed CSV instead of a persistent source_record_id, which would break historical re-runs",
        "persistence": "occasional",
        "support_recommendation": "When introducing or modifying seed files that reference external dataset identifiers, Data should confirm in the PR whether the key is versioned or persistent and call it out explicitly. A brief documentation note in the seed CSV header or a schema.yml description field explaining the key type would help catch this earlier."
      }
    ]
  },
  {
    "login": "LaForge",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Broad infrastructure ownership: confidently ships across CI/CD workflows, Terraform, Airflow DAGs, Docker images, and dbt \u2014 demonstrating end-to-end platform fluency",
        "persistence": "consistent"
      },
      {
        "area": "Responsive to reviewer feedback: quickly addresses inline comments (typos, config placement, path mismatches) within the same review cycle rather than deferring to follow-up PRs",
        "persistence": "consistent"
      },
      {
        "area": "Proactive deprecation and cleanup work: regularly removes legacy artifacts, deprecated buckets, and outdated workflows without being prompted (PRs #5139, #5239, #5078)",
        "persistence": "consistent"
      },
      {
        "area": "Pairs effectively with senior engineers (O'Brien, Scott) and incorporates pairing output directly into merged PRs, indicating strong collaborative learning habits",
        "persistence": "consistent"
      }
    ],
    "growth_areas": [
      {
        "area": "dbt model config placement: in PR #4932 a reviewer had to point out that model config should live in the SQL file rather than the YAML file, which is a dbt best-practice for keeping source-of-truth config co-located with the model",
        "persistence": "occasional",
        "support_recommendation": "Run a short workshop or share the dbt style guide section on config blocks; have LaForge audit existing models for misplaced configs and open a cleanup PR as a learning exercise"
      },
      {
        "area": "Test coverage and fixture accuracy for new operators: PR #5307 had multiple reviewer-caught issues \u2014 wrong file extension in test fixture, test fixture path not matching production DAG path, and an incorrect return type annotation \u2014 suggesting tests are written quickly without validating fixture/path parity against real outputs",
        "persistence": "consistent",
        "support_recommendation": "Establish a pre-PR checklist item: run tests locally and confirm fixture file names, paths, and return types exactly match the operator's production logic before marking ready for review; pair once on a test-writing session focused on fixture design"
      },
      {
        "area": "YAML source definition accuracy: PR #5307 noted that _src_tides.yml had fields not matching outcomes.yml, indicating source YAML is sometimes written without cross-checking against actual schema outputs",
        "persistence": "occasional",
        "support_recommendation": "When defining new sources, use `dbt run-operation generate_source` or manually diff the schema YAML against a sample of the real data before opening the PR; add this as a step in the team's new-source checklist"
      },
      {
        "area": "CI credential and environment variable hygiene: PR #4892 shows uncertainty about which GCP credentials to use in a workflow, defaulting back to a legacy secret after an attempted change failed without a clear understanding of why",
        "persistence": "occasional",
        "support_recommendation": "Provide a written reference mapping each GCP workflow secret to its purpose and valid contexts; schedule a 30-minute walkthrough of the team's secrets management approach so LaForge can confidently make credential changes rather than reverting"
      }
    ]
  },
  {
    "login": "O'Brien",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Incremental, safe infrastructure rollout \u2014 consistently uses pausing, staging-first, and phased deployment patterns (e.g., paused scheduler job before unpausing, staging resource tuning before prod)",
        "persistence": "consistent"
      },
      {
        "area": "Clean-up discipline \u2014 proactively removes stale or deprecated resources (old service accounts, pre-v3 archiver SA, unused k8s resources) as part of related PRs",
        "persistence": "consistent"
      },
      {
        "area": "Infrastructure-as-code hygiene with Terraform \u2014 consistent use of Terraform for GCP resources (Cloud SQL, GCS, IAM, Cloud Scheduler, Composer, SFTP cluster) with targeted, narrowly scoped PRs",
        "persistence": "consistent"
      },
      {
        "area": "Testability focus \u2014 added unit tests for GTFS-RT archiver modules and structured code to be locally testable",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Stakeholder alignment and formal migration planning before production changes \u2014 two PRs (#4491, #5128) received dismissed reviews from evansiroky citing lack of a documented testing/migration plan for high-criticality data pipelines; changes proceeded without fully resolving the concern",
        "persistence": "consistent",
        "support_recommendation": "Before beginning implementation of changes to high-criticality data collection systems, co-author a one-page migration plan with the relevant stakeholder (e.g., evansiroky) that specifies: a minimum parallel-run window (\u22652 weeks), success criteria, rollback steps, and sign-off. Make this plan a required artifact linked in the PR description."
      },
      {
        "area": "PR descriptions lack context for reviewers \u2014 multiple approvals include reviewer uncertainty ('Not 100% sure about this but I think it's okay', 'I understand parts of this', 'I can't see why it would destroy things'), suggesting PR descriptions do not consistently explain the 'why', risk surface, or expected Terraform plan outcomes",
        "persistence": "consistent",
        "support_recommendation": "Adopt a lightweight PR description template that includes: (1) problem being solved, (2) summary of changes and any non-obvious decisions, (3) expected Terraform plan summary or diff highlights, and (4) testing steps or verification evidence. Review two past PRs with a senior teammate to calibrate the expected detail level."
      },
      {
        "area": "Terraform formatting errors not caught before review \u2014 reviewer noted a Terraform formatting error in PR #5135 that slipped through",
        "persistence": "occasional",
        "support_recommendation": "Add a pre-commit hook or CI step that runs `terraform fmt -check` and `terraform validate` on all changed .tf files so formatting issues are caught automatically before review."
      }
    ]
  },
  {
    "login": "Rand",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Operational execution and throughput: consistently ships multiple related PRs in tight clusters (e.g., five PRs on 2026-04-15 and 2026-04-29/30) with clean approvals, indicating strong ability to decompose work and land incremental changes",
        "persistence": "consistent"
      },
      {
        "area": "Documentation authorship: produces comprehensive workflow and onboarding documentation that reviewers consistently describe as 'really good' and containing all necessary information",
        "persistence": "consistent"
      },
      {
        "area": "Responsive to review feedback: addresses inline comments and updates PRs promptly, as evidenced by direct responses to reviewer questions in PR #4570 and iterating through changes in PR #5113",
        "persistence": "consistent"
      },
      {
        "area": "Cross-functional awareness: raises clarifying questions on own PRs (PR #4570) about correctness of field references, security practices, and data lineage, showing analytical thoroughness",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Precision of field-level and schema documentation in dbt YAML: reviewers repeatedly flag unnecessary or incorrect fields in mart and staging YAML files (PR #5284 \u2014 multiple fields flagged as irrelevant or not used: PRN, PAR, code parsed as string reintroducing a known bug #4965), indicating documentation is written but not always validated against current data contracts",
        "persistence": "consistent",
        "support_recommendation": "Before opening a PR that touches _model_.yml files, do a pass cross-referencing each documented column against the upstream source schema and any open bugs. Create a personal checklist: (1) Is this field currently populated? (2) Is there an open issue about this field? (3) Has the data type been verified against the source? Pair with Spock on one PR to walk through this validation process."
      },
      {
        "area": "Accuracy of external table and DAG run semantics in documentation: PR #4570 required multiple correction cycles because the documentation misstated when 'create external tables' DAG needs to run \u2014 a conceptual misunderstanding about BigQuery external table creation vs. data scanning that the reviewer flagged as a common source of confusion",
        "persistence": "consistent",
        "support_recommendation": "Schedule a focused knowledge-share session with Spock specifically on BigQuery external table lifecycle (create once vs. run on schedule) and when Airflow DAG reruns are actually required vs. optional. After the session, update the relevant documentation section independently and request a targeted review to confirm the mental model is correct before writing future pipeline documentation."
      },
      {
        "area": "Completeness and specificity of GitHub issue templates and checklists: PR #5113 required a change-request round because the onboarding intake template lacked specific Airtable table/column references, a definition of done, and correct assignee lists \u2014 items that are discoverable from existing documentation",
        "persistence": "consistent",
        "support_recommendation": "When authoring templates or checklists, explicitly include a 'definition of done' section and anchor every reference to a data source to a specific table and column (not just a system name). Before requesting review, walk through the template as if you were a new team member with no context and identify any step where you would need to ask a question \u2014 those are gaps to fill proactively."
      },
      {
        "area": "Idempotency and re-processing considerations in operator design: PR #5184 introduced a parse operator with a hard skip on already-parsed files; reviewer raised a concrete recent counterexample (OCTA re-parse in #5143) showing re-parsing is a legitimate operational need, suggesting the edge case was not fully considered before implementation",
        "persistence": "occasional",
        "support_recommendation": "Before finalizing any operator or pipeline component that introduces a 'skip if already exists' guard, write down the reprocessing scenario explicitly: under what conditions would an operator need to rerun on already-processed data? Document the answer in a code comment or PR description. If the answer is 'never,' justify why. If the answer is 'sometimes,' add a parameter to override the skip."
      }
    ]
  },
  {
    "login": "Spock",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Systematic incremental/microbatch migration: consistently drives large-scale strategy changes (microbatch for dim_stop_arrivals, dim_stop_times, GTFS RT, GTFS Schedule, etc.) with clear runbook documentation",
        "persistence": "consistent"
      },
      {
        "area": "Cross-domain ownership: comfortably works across Payments, GTFS Schedule, and GTFS RT model families, delivering fixes, migrations, and new features in each",
        "persistence": "consistent"
      },
      {
        "area": "Bug identification and remediation: proactively catches and fixes data quality issues alongside migrations (e.g., old message age calculation bug in #5065, RT index join fix in #5051, deduplication via feed_version in #4860)",
        "persistence": "consistent"
      },
      {
        "area": "Re-enabling and expanding dbt test coverage: restores disabled tests (#5036) and fixes failing tests (#5145), demonstrating commitment to data reliability",
        "persistence": "consistent"
      },
      {
        "area": "Documentation and runbook upkeep: updates incremental model documentation as part of migration work (#5178), keeping docs in sync with implementation",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Merge conflict management: PRs flagged with active merge conflicts before reviewer approval (e.g., #4863), suggesting changes are not always rebased or conflicts resolved prior to review request",
        "persistence": "occasional",
        "support_recommendation": "Establish a personal checklist to run `git fetch` and rebase against main before requesting review; consider enabling branch protection rules that block review on conflicting branches."
      },
      {
        "area": "Pre-merge validation of test results: multiple PRs approved conditionally pending test passage (e.g., #4894 'Make sure tests pass before implementing', #4863 'This might break things but we need to try'), indicating tests are not always confirmed green before merging",
        "persistence": "consistent",
        "support_recommendation": "Ensure CI pipeline runs `dbt build --select state:modified+` on every PR and is required to pass before merge; pair with reviewer to walk through reading CI output so test failures are caught and resolved by the author before approval is requested."
      },
      {
        "area": "Residual unexplained test failures post-fix: even after dedicated test-fix PRs (e.g., #5145), reviewers note lingering staging failures (e.g., unique test on stg_littlepay__product_data_v3) that the author has not fully diagnosed",
        "persistence": "occasional",
        "support_recommendation": "When opening a test-fix PR, include a section in the PR description listing each previously failing test and confirming it passes in staging; schedule a pairing session with Troi or LaForge to work through root-cause analysis of any residual failures before closing the ticket."
      },
      {
        "area": "Schema change handling completeness: a dedicated follow-up PR (#5076) was needed to set schema change behavior that should have been included in the original conversion PR (#5065), suggesting schema change config is sometimes overlooked during microbatch migrations",
        "persistence": "occasional",
        "support_recommendation": "Add `on_schema_change` to the microbatch migration checklist/template so it is reviewed as a mandatory step in every conversion PR, avoiding follow-up patches."
      }
    ]
  },
  {
    "login": "Uhura",
    "trajectory": "improving",
    "strengths": [
      {
        "area": "Consistent delivery of well-scoped, reviewable PRs that receive clean approvals with minimal revision cycles",
        "persistence": "consistent"
      },
      {
        "area": "Receptiveness to reviewer feedback \u2014 when suggestions are offered (e.g., QUALIFY refactor, partial/chaining in Airflow DAG), the author adopts them promptly and articulates the reasoning",
        "persistence": "consistent"
      },
      {
        "area": "Incremental, layered model building: staging \u2192 mart \u2192 fact models follow dbt's recommended layering pattern across the Airtable issue management feature",
        "persistence": "consistent"
      },
      {
        "area": "Self-review and proactive code quality improvement \u2014 author participates in their own PR reviews and suggests cleaner alternatives (QUALIFY suggestion on PR #5062)",
        "persistence": "emerging"
      },
      {
        "area": "Clear documentation practice \u2014 dedicated README PR (#5057) accompanies the feature build",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Airflow DAG task dependency structuring \u2014 PR #5182 required reviewer guidance to consolidate task chaining rather than looping, and to use `partial` for cleaner operator parameterization",
        "persistence": "occasional",
        "support_recommendation": "Review the Airflow documentation on `functools.partial` with operators and study examples of dynamic task mapping (`.expand()`). A code review pairing session on DAG design patterns in the existing repo would accelerate internalization."
      },
      {
        "area": "Failure-handling strategy in DAGs \u2014 reviewer flagged that trigger rules (e.g., TriggerRule.ALL_DONE) could enable more robust email reporting; author deferred rather than exploring the tradeoff fully",
        "persistence": "occasional",
        "support_recommendation": "Walk through the repo's existing failure-handling patterns (on_failure_callback, email_on_failure) alongside Airflow's TriggerRule documentation to build a mental model for when partial-success reporting is appropriate vs. all-or-nothing."
      },
      {
        "area": "SQL deduplication patterns \u2014 required external reviewer input (PR #5062) to discover the QUALIFY approach over array-based deduplication, suggesting gaps in awareness of window-function idioms",
        "persistence": "occasional",
        "support_recommendation": "Add a SQL patterns reference doc or internal wiki entry on deduplication idioms (QUALIFY, ROW_NUMBER, DISTINCT ON) used in the warehouse. Consider a short pairing session on BigQuery-specific SQL features."
      }
    ]
  },
  {
    "login": "Chekov",
    "trajectory": "stable",
    "strengths": [
      {
        "area": "Iterative problem-solving: addresses recurring false-alarm/threshold issues across multiple PRs with targeted parameter tuning",
        "persistence": "consistent"
      },
      {
        "area": "Safe, incremental deployments: uses staging environments before promoting changes (e.g., Composer 3 staging PR before production migration)",
        "persistence": "emerging"
      },
      {
        "area": "Responsive to reviewer feedback: acts quickly on requested changes (e.g., revert PR #5340 following staging test results)",
        "persistence": "consistent"
      }
    ],
    "growth_areas": [
      {
        "area": "PR description precision: using GitHub closing keywords (e.g., 'Resolves') incorrectly, which can prematurely close issues that are still in progress",
        "persistence": "occasional",
        "support_recommendation": "Add a team-level PR template or checklist that explicitly distinguishes 'Resolves #X' (closes ticket) from 'Working towards #X' (partial progress), and include a brief note in onboarding docs about GitHub auto-close keywords."
      },
      {
        "area": "Reviewer confidence signals: multiple approvals include hedging language ('it should be okay', 'Let's see how it goes'), suggesting PRs may lack sufficient context, tests, or validation evidence for reviewers to approve confidently",
        "persistence": "consistent",
        "support_recommendation": "Encourage Chekov to include in each PR description: (1) how the change was validated locally or in staging, (2) what the expected before/after behavior is, and (3) any relevant metrics or logs that confirm the fix. A PR description template with these sections would help."
      },
      {
        "area": "Root cause documentation: threshold/parameter tuning PRs (#4856, #4888) lack documented rationale for specific values chosen, making future debugging harder",
        "persistence": "consistent",
        "support_recommendation": "Pair Chekov with a senior engineer to co-author a short post-mortem or ADR (Architecture Decision Record) for one of the false-alarm tuning PRs, establishing the habit of documenting 'why this value' alongside 'what changed'."
      }
    ]
  },
  {
    "login": "Scott",
    "trajectory": "stable",
    "strengths": [
      {
        "area": "Rapid iteration and hotfix delivery: repeatedly ships targeted fixes (dim_stop_latest duplicate fix, urllib3 pin/revert, NTD external table fix) with clear scope and minimal blast radius",
        "persistence": "consistent"
      },
      {
        "area": "Cross-functional collaboration and live debugging: works directly with reviewers (e.g., live pairing on dim_stop_latest) and leaves self-comments on own PRs to surface issues proactively",
        "persistence": "consistent"
      },
      {
        "area": "Infrastructure and operations work: consistently handles Kubernetes node pool scaling, IAM permission management, Composer environment config, and GCS bucket provisioning with approvals and no revision cycles",
        "persistence": "consistent"
      },
      {
        "area": "Incremental and sequential pipeline fixes: demonstrates understanding of incremental model behavior (dbt_short_name PR) and data pipeline ordering (Elavon sequential operations)",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Root cause analysis before merging: multiple PRs are approved with explicit callouts that the underlying issue is not fully diagnosed (dim_stop_latest duplicate hotfix, fct_tides_vehicle_locations performance). Fixes land without follow-up tickets being formally tracked.",
        "persistence": "consistent",
        "support_recommendation": "Establish a team norm that every hotfix PR includes a linked follow-up GitHub issue in the PR description before merge. Pair with Spock or LaForge to template a 'hotfix checklist' that includes root-cause investigation as a mandatory follow-up step."
      },
      {
        "area": "Model layer placement and mart/intermediate boundaries: fct_tides_vehicle_locations was placed in the mart folder as a view, which reviewers flagged as a misplacement that could expose it in Metabase and risk full-table scans on large upstream tables",
        "persistence": "occasional",
        "support_recommendation": "Review the team's layer conventions document together with LaForge. Practice a pre-PR checklist: 'Is this model materialized correctly for its layer? Will it appear in Metabase? Does it create unbounded scan risk?' Consider adding a linting rule or PR template question for mart-layer materialization type."
      },
      {
        "area": "Dependency and environment pinning strategy: pinned urllib3<2.0 to fix a Composer 3 crash, then had to immediately revert because the pin broke the staging deploy, indicating insufficient cross-environment testing before pinning",
        "persistence": "occasional",
        "support_recommendation": "Work with Chekov to establish a standard process for dependency changes: test pin in staging first, document the security vs. compatibility tradeoff in the PR, and identify the correct compatible version range before merging to any environment. Create a team runbook for dependency bumps."
      },
      {
        "area": "YAML/configuration hygiene: self-caught that adding and updating ckan 'id' fields was unnecessary since the field is unused in the current DAG, suggesting configuration changes are sometimes made without verifying downstream usage",
        "persistence": "occasional",
        "support_recommendation": "Before adding or modifying YAML fields (sources, exposures, meta), trace the field's usage in at least one downstream consumer (DAG, BI tool, or published artifact). Add a self-review checklist item: 'Is every field I changed actually consumed somewhere?'"
      }
    ]
  },
  {
    "login": "Sulu",
    "trajectory": "stable",
    "strengths": [
      {
        "area": "Incremental, focused PRs: work is consistently broken into small, single-purpose changes (e.g., separate PRs for service accounts, buckets, deployments, and static IPs for the Elavon SFTP rollout)",
        "persistence": "consistent"
      },
      {
        "area": "Cross-functional delivery: able to ship infrastructure, DAG, and image-layer changes across the stack (Kubernetes, Terraform, Composer/Airflow, JupyterHub) without blocking on others",
        "persistence": "consistent"
      },
      {
        "area": "Clean approval signal: all 13 PRs were approved, often with minimal or no substantive review comments, indicating work generally meets reviewer expectations on first pass",
        "persistence": "consistent"
      }
    ],
    "growth_areas": [
      {
        "area": "Incomplete environment parity: PR #5032 received two related inline comments noting that a parallel Composer 3 environment on the same Terraform file was not updated alongside the Composer 2 change, suggesting a pattern of updating only the targeted resource without auditing sibling resources in the same file",
        "persistence": "occasional",
        "support_recommendation": "Add a personal checklist item before opening infra PRs: scan the full file for parallel environment definitions (e.g., c2 vs c3, staging vs prod) and either update them or explicitly note in the PR description why they are intentionally excluded. Pair with Scott on one IaC PR to walk through the environment-parity review process."
      },
      {
        "area": "PR descriptions are sparse: several PRs have titles that are truncated or vague (e.g., 'New jupyterhub image with minimal dependencies and pyproject-local-ke\u2026'), making it hard to assess intent, scope, or rollback plan from the PR list alone",
        "persistence": "consistent",
        "support_recommendation": "Adopt a lightweight PR description template (What, Why, How to verify) and apply it to all PRs. Even two to three sentences per section would materially improve reviewability and the audit trail."
      },
      {
        "area": "Reviewer concentration: 11 of 13 PRs were reviewed solely by LaForge, creating a single-reviewer dependency and limiting exposure to broader team feedback",
        "persistence": "consistent",
        "support_recommendation": "Proactively request a second reviewer on PRs touching shared infrastructure (Composer, Kubernetes, Terraform). Rotate to Scott or O'Brien as primary reviewer at least once per sprint to build redundant code familiarity across the team."
      }
    ]
  },
  {
    "login": "Worf",
    "trajectory": "stable",
    "strengths": [
      {
        "area": "Infrastructure decommissioning and cleanup: consistently delivers focused, well-scoped PRs that remove components cleanly (Metabase, Grafana/Prometheus/Loki, Sentry, archiver deployments) without scope creep",
        "persistence": "consistent"
      },
      {
        "area": "Rapid iteration and follow-up: demonstrates ability to identify and fix issues immediately (e.g., PR #5209 fixing patch targets scoped to kind:Deployment shortly after #5194), showing strong self-review habits",
        "persistence": "consistent"
      },
      {
        "area": "Security and operational hygiene: proactively applies security patches (JupyterHub 3.3.7\u21923.3.8), sets up monitoring replacements before decommissioning in-cluster stacks, and adds runbooks for restore procedures",
        "persistence": "consistent"
      },
      {
        "area": "High PR throughput with consistent approvals: 16 PRs all approved across a short window (~9 weeks), indicating reliable, reviewable work product",
        "persistence": "consistent"
      }
    ],
    "growth_areas": [
      {
        "area": "Reviewer comprehension gaps: multiple reviewer comments indicate the reviewer does not fully understand the change (Scott: 'I don't understand but this should be okay'), suggesting PRs may lack sufficient context, descriptions, or inline comments to support non-expert review",
        "persistence": "consistent",
        "support_recommendation": "Establish a PR description template requiring: (1) a plain-language summary of what changed and why, (2) relevant background links or runbook references, (3) expected observable outcome or how to verify. Pair with a team norm that reviewers should request clarification rather than approving without understanding."
      },
      {
        "area": "Merge conflict and CI hygiene: at least one PR (#5245) was flagged for unresolved merge conflicts and failing checks at time of approval request, indicating the author sometimes seeks review before the branch is fully ready",
        "persistence": "occasional",
        "support_recommendation": "Add a branch protection rule requiring status checks to pass before review can be completed, and/or adopt a personal checklist habit (rebase, check CI green) before moving a PR to 'ready for review' state."
      },
      {
        "area": "Reviewer diversity: the vast majority of PRs are reviewed by a single reviewer (Scott), with only occasional involvement from O'Brien, LaForge, or Spock \u2014 this creates a single point of failure for knowledge transfer and review quality",
        "persistence": "consistent",
        "support_recommendation": "For infrastructure decommissioning or migration PRs, require a second reviewer assignment policy. Rotate review responsibility across the team on a scheduled basis to spread context and reduce dependency on one reviewer."
      }
    ]
  },
  {
    "login": "Crusher",
    "trajectory": "insufficient-data",
    "strengths": [
      {
        "area": "Broad scope of contributions spanning aggregation logic, rollup models, and dbt documentation in a cohesive domain (mart_gtfs / mart_gtfs_rollup)",
        "persistence": "consistent"
      },
      {
        "area": "Attention to correctness in edge cases \u2014 catching and fixing operator summary issues when schedules have multiple RT feeds, and propagating service_hours/flex_service_hours consistently across models",
        "persistence": "consistent"
      },
      {
        "area": "Proactive documentation hygiene \u2014 dedicated PR to add dbt docs for new models, positively noted by a second reviewer",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Depth of reviewer feedback is very limited across all 4 PRs \u2014 only one substantive inline comment exists in the entire window, making it difficult to assess code quality gaps from review signal alone",
        "persistence": "consistent",
        "support_recommendation": "Encourage reviewers (particularly jiaxiliu95 who approves all PRs) to leave inline comments on logic, grain, and naming choices so growth areas surface. Consider adding a second mandatory reviewer from outside the immediate team for cross-functional PRs."
      },
      {
        "area": "No evidence of testing coverage being added or updated alongside new/changed models",
        "persistence": "consistent",
        "support_recommendation": "Establish a team norm that each PR touching mart or rollup models must include or update schema.yml tests (not_null, unique, accepted_values, relationships). Add a PR checklist item for test coverage and have the reviewer explicitly confirm it before approving."
      },
      {
        "area": "No visible use of dbt model contracts, versioning, or exposure definitions for mart-layer models that appear to be consumer-facing",
        "persistence": "consistent",
        "support_recommendation": "Introduce a team discussion on adopting dbt model contracts (enforce: true) for stable mart models. Pair Crusher with a senior analyst to audit which mart_gtfs models are downstream-consumed and add exposures.yml entries for those, then layer in contracts incrementally."
      }
    ]
  },
  {
    "login": "Guinan",
    "trajectory": "insufficient-data",
    "strengths": [],
    "growth_areas": []
  },
  {
    "login": "Ro",
    "trajectory": "insufficient-data",
    "strengths": [
      {
        "area": "Iterative responsiveness to reviewer feedback: consistently revisits implementation after initial misunderstanding and pushes corrected commits (e.g., PR #5164 pivoting from exclude to allowlist approach after reviewer clarification)",
        "persistence": "consistent"
      },
      {
        "area": "CI/CD and workflow configuration work: multiple PRs address dbt deployment pipeline correctness (dependency ordering, Metabase sync scoping, Dependabot skip logic)",
        "persistence": "consistent"
      },
      {
        "area": "Bug fix PRs are small, focused, and quickly approved with minimal back-and-forth (PRs #5241, #5256, #5346)",
        "persistence": "consistent"
      }
    ],
    "growth_areas": [
      {
        "area": "Incomplete requirements analysis before opening a PR: PR #5164 was submitted without fully understanding the multi-database scope of the issue, requiring a rework after reviewer clarification",
        "persistence": "occasional",
        "support_recommendation": "Before opening a PR for infrastructure or workflow changes, write a brief problem statement in the PR description that explicitly maps the proposed change to every affected system or database instance. Ask a senior reviewer or the ticket author to validate the scope before writing code."
      },
      {
        "area": "Limited evidence of proactive dbt modeling standards awareness (e.g., staging/mart layer separation, model naming conventions, source freshness) \u2014 the PRs reviewed are mostly CI/workflow fixes, making it hard to assess SQL/dbt modeling depth",
        "persistence": "occasional",
        "support_recommendation": "Pair with a senior analytics engineer on the next mart or intermediate model PR to review naming conventions, materialization choices, and documentation requirements. Complete the dbt Learn 'Jinja, Macros, Analysis' and 'Advanced Materializations' modules if not already done."
      }
    ]
  },
  {
    "login": "Troi",
    "trajectory": "insufficient-data",
    "strengths": [],
    "growth_areas": []
  }
];

  const gaps = [
  {
    "area": "Superficial 'LGTM' approvals on high-risk SQL changes with no inline technical scrutiny",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "The Checklist Manifesto: breaking changes and fact/transaction model additions warrant checklist-driven review covering grain, tests, and downstream impact",
    "recommendation": "Add a PR checklist template for fact/transaction model changes requiring explicit sign-off on: join logic, grain definition, filter correctness, and downstream model impact. Gate merge on at least one inline technical comment for PRs labeled 'breaking change' or touching fct_ models."
  },
  {
    "area": "dbt model configuration review \u2014 materialization strategy, incremental strategy, and unique_key correctness",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "dbt Labs style guide: incremental models require explicit unique_key and incremental_strategy; dbt-project-evaluator: fct_missing_primary_key_tests, model_fanout checks",
    "recommendation": "Add a CI gate using dbt-project-evaluator checks (missing_primary_key_tests, model_fanout) and include materialization/incremental strategy review as a mandatory checklist item for any PR touching model configs."
  },
  {
    "area": "Referential integrity and upstream/downstream lineage impact analysis",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "dbt Labs style guide: use ref() and source() macros; dbt-project-evaluator: direct_join_to_source, downstream_models_not_null checks",
    "recommendation": "Require reviewers to run or cite dbt lineage graph output (dbt ls --select +model+) in PR descriptions for any model addition or rename. Add dbt-project-evaluator direct_join_to_source as a CI check."
  },
  {
    "area": "Defined rollback plan and success criteria before merging live pipeline changes",
    "gap_type": "knowledge_gap",
    "criticality": 3,
    "standard_citation": "The Checklist Manifesto: define rollback criteria and monitoring thresholds before merging live pipeline changes",
    "recommendation": "Create a formal 'data pipeline change' PR template requiring: success criteria, rollback procedure, and monitoring threshold fields. Treat 'merge and watch' as a non-compliant review pattern; flag it in code review training."
  },
  {
    "area": "Test pyramid coverage \u2014 integration and end-to-end tests for data-critical pipeline code, not just unit tests",
    "gap_type": "knowledge_gap",
    "criticality": 3,
    "standard_citation": "The Checklist Manifesto: confirm test pyramid coverage (unit + integration + e2e) before merging data-critical pipeline code",
    "recommendation": "Document the expected test pyramid for each pipeline category (infrastructure change, dbt model, Airflow DAG). Add a CI gate requiring at least one integration test execution result to be linked in PRs touching production data feeds."
  },
  {
    "area": "Reviewer approval with self-acknowledged partial comprehension",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": null,
    "recommendation": "Establish a team norm that partial-comprehension approvals must be labeled as 'conditional' and require a second reviewer with domain expertise before merge. Add this to the contributing guide and PR template."
  },
  {
    "area": "Formal SLA and reliability requirements documentation for real-time data pipelines",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": null,
    "recommendation": "Define and document SLA requirements (uptime, latency, data freshness) for RT data archiving pipelines in a dedicated ADR or runbook before any migration PR is opened. Require a link to this document in migration PRs."
  },
  {
    "area": "Independent verification of Terraform plan outputs by reviewers",
    "gap_type": "knowledge_gap",
    "criticality": 3,
    "standard_citation": null,
    "recommendation": "Require Terraform plan output to be pasted or linked in the PR body (not just described). Add a CI step that generates and archives terraform plan output as a required status check so reviewers can inspect it independently."
  },
  {
    "area": "dbt source freshness and data recency testing",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "dbt Labs style guide: define source freshness checks on all sources; dbt-project-evaluator: missing_source_freshness check",
    "recommendation": "Add dbt-project-evaluator missing_source_freshness as a CI check. Include 'source freshness thresholds defined?' as a checklist item for any PR adding or modifying dbt sources."
  },
  {
    "area": "SQL style consistency enforcement (aliasing, CTE structure, trailing commas)",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "SQLFluff rules: L011 (implicit aliasing), L022 (blank lines around CTEs), L036 (single column per SELECT line), dbt Labs style guide: CTE naming and structure conventions",
    "recommendation": "Integrate SQLFluff with the dbt Labs dialect into CI as a required linting gate. Add a .sqlfluff config file to the repository enforcing the team's chosen rules and block merges on lint failures."
  },
  {
    "area": "Breaking change migration communication and downstream consumer notification",
    "gap_type": "knowledge_gap",
    "criticality": 3,
    "standard_citation": "dbt Labs style guide: document breaking changes in CHANGELOG; communicate schema changes to downstream consumers",
    "recommendation": "Require a CHANGELOG entry and a list of downstream consumers/teams to notify as mandatory fields in the PR template for any PR tagged 'breaking change'. Add a review checklist item to verify this is complete."
  }
];

  return {
    repo:            "cal-itp/data-infra",
    window:          "2026-03-02 \u2192 2026-05-30",
    pr_count:        190,
    prs_with_reviews: 182,
    contributors:    ["Rand", "Data", "LaForge", "Uhura", "Ro", "Sulu", "Spock", "Troi", "O'Brien", "Bashir", "Guinan", "Worf", "Crusher", "Chekov", "Scott"],
    visibility:      "demo",
    version:         "1.0.0.1",
    CATEGORIES,
    RADAR_CATEGORIES,
    CATEGORY_GROUP,
    patterns,
    reviewers,
    authors,
    gaps,
  };
})();
