// Generated by tricorder build — 2026-06-08 18:50
// Repo: dhk/adventures-in-ai  |  Version: 1.0.1.3
window.TRICORDER_DATA = (function () {

  const CATEGORIES = ["grain", "naming", "testing", "documentation", "style", "performance", "modeling", "schema", "business-logic", "structure", "security", "other"];
  const RADAR_CATEGORIES = CATEGORIES;
  const CATEGORY_GROUP = {"grain": "data", "naming": "pattern", "testing": "tool", "documentation": "pattern", "style": "pattern", "performance": "data", "modeling": "data", "schema": "data", "business-logic": "pattern", "structure": "pattern", "security": "tool", "other": "pattern"};

  const patterns = [
  {
    "signal": "Typo in prose documentation ('specificy' instead of 'specific')",
    "category": "documentation",
    "maturity": "deterministic",
    "standard_citation": null,
    "reviewer": "Copilot",
    "author": "dhk",
    "evidence": [
      {
        "pr": "",
        "date": "",
        "author": "dhk",
        "quote": "Fix typo: change 'specificy' to 'specific'."
      }
    ]
  },
  {
    "signal": "Typo in prose documentation ('decisosn' instead of 'decisions')",
    "category": "documentation",
    "maturity": "deterministic",
    "standard_citation": null,
    "reviewer": "Copilot",
    "author": "dhk",
    "evidence": [
      {
        "pr": "",
        "date": "",
        "author": "dhk",
        "quote": "Fix typo: change 'decisosn' to 'decisions'."
      }
    ]
  },
  {
    "signal": "Typo in README documentation ('Figre' instead of 'Figure')",
    "category": "documentation",
    "maturity": "deterministic",
    "standard_citation": null,
    "reviewer": "Copilot",
    "author": "dhk",
    "evidence": [
      {
        "pr": "",
        "date": "",
        "author": "dhk",
        "quote": "Fix typo: change 'Figre' to 'Figure'."
      }
    ]
  },
  {
    "signal": "PR submitted without a description, making change intent opaque",
    "category": "documentation",
    "maturity": "convention",
    "standard_citation": "GitHub Pull Request best practices: PRs should include a description explaining the purpose of the change",
    "reviewer": "Copilot",
    "author": "dhk",
    "evidence": []
  }
];

  const reviewers = [
  {
    "login": "Copilot",
    "review_style": "terse",
    "signal_quality": "low",
    "primary_focus_areas": [
      {
        "area": "Spelling and typo correction in prose/documentation",
        "frequency": "always"
      }
    ],
    "apparent_blind_spots": [
      {
        "area": "Structural or content quality of documentation (e.g., completeness, accuracy, clarity of explanations)",
        "basis": "All three comments are mechanical spell-fixes; no feedback was given on the substance, organization, or correctness of the documentation content."
      },
      {
        "area": "Grammar and punctuation beyond simple misspellings",
        "basis": "Only character-level typos were flagged; no sentence-level grammar or punctuation issues were raised despite documentation-heavy PR."
      },
      {
        "area": "Code or configuration review",
        "basis": "PR contained only documentation; no evidence of how Copilot handles non-documentation files, making this a blind spot by absence of signal."
      }
    ],
    "category_freq": {
      "grain": 8,
      "naming": 8,
      "testing": 8,
      "documentation": 90,
      "style": 8,
      "performance": 8,
      "modeling": 8,
      "schema": 8,
      "business-logic": 8,
      "structure": 8,
      "security": 8,
      "other": 8
    }
  }
];

  const authors = [
  {
    "login": "dhk",
    "trajectory": "insufficient-data",
    "strengths": [
      {
        "area": "Attention to typographical detail in documentation",
        "persistence": "emerging"
      }
    ],
    "growth_areas": [
      {
        "area": "Code contributions beyond documentation \u2014 no code-level changes visible across reviewed PRs",
        "persistence": "occasional",
        "support_recommendation": "Pair with a more experienced contributor on a small feature or bug fix to build comfort making code-level changes; set a goal of at least one non-documentation PR per sprint."
      },
      {
        "area": "Insufficient review data to assess patterns \u2014 only 1 of 16 PRs has visible inline feedback",
        "persistence": "consistent",
        "support_recommendation": "Ensure all PRs go through structured code review with written inline comments so a meaningful growth profile can be built; use a PR template that requires reviewers to leave at least one substantive comment per PR."
      }
    ]
  }
];

  const gaps = [
  {
    "area": "PR description and change intent documentation",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "GitHub Pull Request best practices: PRs should include a description explaining the purpose of the change",
    "recommendation": "checklist \u2014 enforce a PR template with required fields (Summary, Motivation, Testing Notes) via GitHub's PULL_REQUEST_TEMPLATE.md; consider a branch-protection rule or CI-gate that blocks merge if description is empty"
  },
  {
    "area": "Documentation content quality: completeness, accuracy, and clarity of explanations",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "Google Developer Documentation Style Guide: documentation should be complete, accurate, and written for the intended audience",
    "recommendation": "checklist \u2014 add a documentation review checklist item requiring reviewers to assess whether each section is complete, accurate, and comprehensible to the target reader, not merely spell-correct"
  },
  {
    "area": "Grammar, sentence structure, and punctuation beyond character-level typos",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "Microsoft Writing Style Guide: clear, grammatically correct sentences improve comprehension",
    "recommendation": "tooling \u2014 integrate a grammar linter (e.g., Vale with a style ruleset, or LanguageTool CI action) into the pipeline to catch sentence-level grammar and punctuation issues automatically, freeing reviewers to focus on substance"
  },
  {
    "area": "Code correctness, logic, and design review",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "Code Review Best Practices (Google Engineering Practices): reviewers should evaluate correctness, design, complexity, and tests",
    "recommendation": "training \u2014 with only one documentation-only PR reviewed by Copilot and no human peer review evident across 16 PRs, the team needs a human code-review process; establish a mandatory second human reviewer policy and train dhk on structured code review using Google's code review guide"
  },
  {
    "area": "Test coverage and testability review",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "Google Engineering Practices \u2013 Code Review: reviewers should verify that tests are present, correct, and meaningful",
    "recommendation": "ci-gate \u2014 add a code coverage threshold gate (e.g., via Codecov or pytest-cov) so test coverage regressions are caught automatically; complement with a checklist item requiring reviewers to confirm new behavior is tested"
  },
  {
    "area": "Security considerations (input validation, dependency vulnerabilities, secrets exposure)",
    "gap_type": "blind_spot",
    "criticality": 2,
    "standard_citation": "OWASP Code Review Guide: every PR should be evaluated for common security risks",
    "recommendation": "tooling \u2014 integrate static analysis security testing (e.g., Semgrep, Bandit for Python, or GitHub's CodeQL) as a CI-gate so security issues surface without relying on reviewer knowledge"
  },
  {
    "area": "Architectural and design fitness of changes",
    "gap_type": "coverage_gap",
    "criticality": 1,
    "standard_citation": "Google Engineering Practices \u2013 Code Review: reviewers should assess whether the design integrates well with the rest of the system",
    "recommendation": "training \u2014 introduce lightweight Architecture Decision Records (ADRs) so design intent is captured before implementation; require at least one human reviewer with domain context to sign off on design-affecting PRs"
  }
];

  return {
    repo:             "dhk/adventures-in-ai",
    window:           "unknown window",
    pr_count:         16,
    prs_with_reviews: 4,
    contributors:     ["Copilot"],
    visibility:       "private",
    version:          "1.0.1.3",
    CATEGORIES,
    RADAR_CATEGORIES,
    CATEGORY_GROUP,
    patterns,
    reviewers,
    authors,
    gaps,
  };
})();
